table Feedback
	lineageTag: c08280fb-ba7e-4bf2-8252-41be1ad30556

	measure 'Feedback Clicks' = COUNTROWS(Feedback)
		formatString: #,0
		lineageTag: 44f6be30-c532-4296-b563-1f98b6f1d6ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Positive Clicks' =
			CALCULATE (
			    [Feedback Clicks],
			    KEEPFILTERS ( 'Feedback'[Feedback] > 0 )
			)
		formatString: #,0
		lineageTag: 638d6120-deef-44cc-bb62-2fd686abb63c

	measure 'Negative Clicks' = ```
			CALCULATE([Feedback Clicks], 'Feedback'[Feedback] < 0)  
			```
		formatString: #,0
		lineageTag: f9079b0c-6d89-4c14-b19e-5073f60f4be4

	measure 'Dissatisfied Users' = ```
			
			COUNTX(
			    SUMMARIZE(Feedback, Feedback[User Key], Feedback[Report Key]),
			    CALCULATE(
			        VAR max_datetime = MAX(Feedback[Created On])
			        RETURN
			        COUNTROWS(
			            FILTER(
			                ALL(Feedback[Created On], Feedback[Feedback]),
			                -1 = 
			                    CALCULATE (
			                        MAX ( Feedback[Feedback] ),
			                        Feedback[Created On] = max_datetime
			                    )
			            )
			        )
			    )
			)
			    
			
			```
		formatString: #,0
		lineageTag: 6d05d2a3-eda9-4dac-be44-6e41d3763e3d

	measure 'Satisfied Users' = ```
			
			COUNTX(
			    SUMMARIZE(Feedback, Feedback[User Key], Feedback[Report Key]),
			    CALCULATE(
			        VAR max_datetime = MAX(Feedback[Created On])
			        RETURN
			        COUNTROWS(
			            FILTER(
			                ALL(Feedback[Created On], Feedback[Feedback]),
			                1 = 
			                    CALCULATE (
			                        MAX ( Feedback[Feedback] ),
			                        Feedback[Created On] = max_datetime
			                    )
			            )
			        )
			    )
			)
			```
		formatString: #,0
		lineageTag: bff0c325-5aad-41b3-b161-dc0ba307b1b2

	measure 'CSAT (Multiple Responses)' =
			
			DIVIDE ( [Positive Clicks], [Feedback Clicks] )
		formatString: #,0.0%;-#,0.0%;#,0.0%
		lineageTag: 7078ad7a-0342-4342-8300-4fa424f483e3

	measure Respondents = DISTINCTCOUNT(Feedback[User Key])
		formatString: #,0
		lineageTag: 92044a13-9746-4803-ab32-0900ca1f6412

	measure '% Feedback Responses' = DIVIDE([Respondents], [Users])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 1894b01e-2c8a-4409-a75b-28cf14695a4c

	measure 'Average Satisfaction' = CALCULATE(AVERAGE(Feedback[Feedback]), Feedback[Feedback] <> 0)
		lineageTag: 0271fd94-95db-42c1-a404-33ee40afb15c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Max Satisfaction Guage' = 1
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: aed97531-66ef-4e95-8dba-5f4149924b9b

		changedProperty = IsHidden

	measure 'Neutral Users' = ```
			
			COUNTX(
			    SUMMARIZE(Feedback, Feedback[User Key], Feedback[Report Key]),
			    CALCULATE(
			        VAR max_datetime = MAX(Feedback[Created On])
			        RETURN
			        COUNTROWS(
			            FILTER(
			                ALL(Feedback[Created On], Feedback[Feedback]),
			                0 = 
			                    CALCULATE (
			                        MAX ( Feedback[Feedback] ),
			                        Feedback[Created On] = max_datetime
			                    )
			            )
			        )
			    )
			)
			```
		formatString: #,0
		lineageTag: fab44868-d17c-4d4e-9f9d-e753f77bb7d9

	measure 'CSAT (Last Response)' =
			
			VAR _positive_clicks = [Satisfied Users]
			VAR _last_clicks = COUNTROWS(SUMMARIZE(Feedback, Feedback[User Key], Feedback[Report Key]))
			RETURN
			IF ( ISBLANK ( _positive_clicks ), BLANK(), DIVIDE ( _positive_clicks, _last_clicks ) )
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 33c62f16-fde9-46ba-ac07-54158684f68f

	column 'User Key'
		dataType: string
		isHidden
		lineageTag: 11b3df5d-e963-44b1-9763-67181e476479
		summarizeBy: none
		sourceColumn: User Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Feedback
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4811ba54-aeea-4a91-bf23-b30a5e5a38f3
		summarizeBy: none
		sourceColumn: Feedback

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Platform
		dataType: string
		lineageTag: 1ced55c8-6e23-41fc-a8a3-c0761cdf4a8c
		summarizeBy: none
		sourceColumn: Platform

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		lineageTag: 3a2e460b-f4d3-4731-afc6-6c57964fd2e5
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Time
		dataType: dateTime
		isHidden
		formatString: Long Time
		lineageTag: 6d128fb8-7140-4d78-8fbf-249f473f70a9
		summarizeBy: none
		sourceColumn: Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Report Key'
		dataType: string
		isHidden
		lineageTag: 0dd6f575-b457-4aae-97b6-b8e8bc2dd922
		summarizeBy: none
		sourceColumn: Report Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Report Page Key'
		dataType: string
		isHidden
		lineageTag: 76699c0c-1a69-4f05-a914-38d5a8a177c5
		summarizeBy: none
		sourceColumn: Report Page Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Feedback Button'
		dataType: string
		lineageTag: fb4a7ea8-bc94-4956-9793-5f18e599b162
		summarizeBy: none
		sourceColumn: Feedback Button

		annotation SummarizationSetBy = Automatic

	column 'Created On'
		dataType: dateTime
		formatString: General Date
		lineageTag: e83bc427-6a3b-4991-9542-9acfd07564c5
		summarizeBy: none
		sourceColumn: Created On

		annotation SummarizationSetBy = Automatic

	partition Feedback = m
		mode: import
		source =
				let
				    Source = #"Feedback - Base",
				    #"Reordered Columns" = Table.ReorderColumns(Source,{"Report Page Key", "Feedback Button", "Feedback", "Page Index", "User-Agent", "Report Key", "User Key", "Platform",  "Date", "Time", "Created On"}),
				    #"Filtered Rows" = Table.SelectRows(#"Reordered Columns", each not ((Text.StartsWith([Filtered Column], "'PixieFeedback") and not Text.StartsWith([Filtered Column], "'PixieFeedbackSlicer")))),
				    #"Added Conditional Column" = Table.AddColumn(#"Filtered Rows", "Custom", each if Text.StartsWith([Filtered Column], "'PixieFeedbackSlicer") then [Filtered Values] else [Feedback Button]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column",{"Feedback Button"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Custom", "Feedback Button"}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"Filtered Column", "Filtered Values", "Filtered Distinct Count", "User-Agent", "Visual ID", "Page Index"})
				in
				    #"Removed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

