table License
	lineageTag: 6422a6ad-62cf-4fd7-9325-ae3090539c4c

	measure 'Performance License' =
			
			IF (
			    AND (
			        SUM ( License[Capability Performance] ) > 0,
			        SUM ( License[Capability Heatmaps] ) > 0
			    ),
			    "",
			    "Not supported in current subscription"
			)
		lineageTag: a72a983c-58d0-4d2e-8ab0-8ab7781b8af6

		annotation PBI_FormatHint = {"isText":true}

	measure 'Security License' =
			
			IF (
			    SUM ( License[Capability Security] ) > 0,
			    "",
			    "Not supported in current subscription"
			)
		lineageTag: bcce2aa8-e113-40ce-a819-c83c066eab86

		annotation PBI_FormatHint = {"isText":true}

	measure 'User Satisfaction License' =
			
			IF (
			    SUM ( License[Capability User Satisfaction] ) > 0,
			    "",
			    "Not supported in current subscription"
			)
		lineageTag: fef01265-ac47-4224-90b5-d03033a79232

		annotation PBI_FormatHint = {"isText":true}

	measure 'Heatmaps License' =
			
			IF (
			    SUM ( License[Capability Heatmaps] ) > 0,
			    "",
			    "Not supported in current subscription"
			)
		lineageTag: 58bf7218-7566-4143-b818-3ada256cf563

		annotation PBI_FormatHint = {"isText":true}

	measure 'Filtered Values License' =
			
			IF (
			    SUM ( License[Capability Filtered Values] ) > 0,
			    "",
			    "Not supported in current subscription"
			)
		lineageTag: e9ae74d3-b18c-44bb-8d43-fb1c6433eb3c

		annotation PBI_FormatHint = {"isText":true}

	column license_key
		dataType: string
		lineageTag: 617ad128-d39f-4f81-8162-5dcbac3c58ab
		summarizeBy: none
		sourceColumn: license_key

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: eb1470eb-e4c9-48d2-bbe1-5f691dd85a54
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column tier
		dataType: string
		lineageTag: 3928f79b-1a33-4799-b739-65f54353f3b4
		summarizeBy: none
		sourceColumn: tier

		annotation SummarizationSetBy = Automatic

	column message
		dataType: string
		lineageTag: 3d0ce904-84f3-4d5e-a509-643198ec3ced
		summarizeBy: none
		sourceColumn: message

		annotation SummarizationSetBy = Automatic

	column exceeded
		dataType: string
		lineageTag: 3ec31cc8-ce0b-474c-9c4c-549e0c5b5cf2
		summarizeBy: none
		sourceColumn: exceeded

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 5b5a82da-e8f1-4546-81b9-454db5ee8111
		summarizeBy: none
		sourceColumn: updated_at

		annotation SummarizationSetBy = Automatic

	partition License = m
		mode: import
		source =
				let
				    ADLSPathDelimiter = if #"Is SaaS" then "-" else "/",
				    Source = AzureStorage.DataLake(#"Data Lake URL" & ADLSPathDelimiter & #"License Key", [HierarchicalNavigation=true]),
				    LicenseResponse = Json.Document(Source{[Name="license-status.json"]}[Content]),
				    status = LicenseResponse[status],
				    LicenseTable = LicenseResponse,
				    #"Converted to Table" = Record.ToTable(LicenseTable),
				    #"Transposed Table" = Table.Transpose(#"Converted to Table"),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Transposed Table", [PromoteAllScalars=true]),
				    #"Expanded exceeded" = Table.ExpandListColumn(#"Promoted Headers", "exceeded"),
				    res =
				        if status = "active" then
				            #"Expanded exceeded"
				        else
				            error Error.Record("License error" , LicenseResponse[message], "Failed to refresh BI Pixie. "  & LicenseResponse[message]),
				    #"Changed Type" = Table.TransformColumnTypes(res,{{"updated_at", type datetime}, {"message", type text}, {"exceeded", type text}, {"tier", type text}, {"status", type text}, {"license_key", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

