table Managers
	lineageTag: 656a2e02-b871-465b-a9a2-00854636795e

	column 'Region Name'
		dataType: string
		lineageTag: aa53c689-a2cb-4aac-8acb-b9af074ae761
		summarizeBy: none
		sourceColumn: Region Name

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: f790aef9-d6d3-4698-bfcc-0c43d8aeed27
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column Division
		dataType: string
		lineageTag: d7b503a4-d6ad-440a-826b-d77f3f0e007a
		summarizeBy: none
		sourceColumn: Division

		annotation SummarizationSetBy = Automatic

	column 'Person Name'
		dataType: string
		lineageTag: 7632703e-eb0d-46af-8c9b-fff3018f4eec
		summarizeBy: none
		sourceColumn: Person Name

		annotation SummarizationSetBy = Automatic

	column 'Person First Name'
		dataType: string
		lineageTag: 62fdf23a-629c-4698-92f5-202e5de14601
		summarizeBy: none
		sourceColumn: Person First Name

		annotation SummarizationSetBy = Automatic

	column 'Person Middle Name'
		dataType: string
		lineageTag: f2864dfc-d649-4603-abb4-fb26ac905248
		summarizeBy: none
		sourceColumn: Person Middle Name

		annotation SummarizationSetBy = Automatic

	column 'Person Last Name'
		dataType: string
		lineageTag: f66aaf90-1bcf-4728-8a8b-7ee91454e89c
		summarizeBy: none
		sourceColumn: Person Last Name

		annotation SummarizationSetBy = Automatic

	column 'Job Title'
		dataType: string
		lineageTag: 73cff03e-cee7-48a8-b2ee-5fec43612695
		summarizeBy: none
		sourceColumn: Job Title

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 38a22914-8dbe-4770-80a9-f7e79819afec
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 150192c0-4543-4606-87f5-f92cdc4bc09a
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Employee ID'
		dataType: string
		lineageTag: db714201-d763-45ae-8b6a-2d34a7fad1b0
		summarizeBy: none
		sourceColumn: Employee ID

		annotation SummarizationSetBy = Automatic

	partition Managers = m
		mode: import
		queryGroup: Users
		source =
				let
				    Source = #"Internal Users - Base",
				    #"Filtered Rows" = Table.SelectRows(Source, each [Employee ID] <> null and [Employee ID] <> ""),
				    #"Merged Queries1" = Table.NestedJoin(#"Filtered Rows", {"Employee ID"}, #"Internal Users - Base", {"Manager ID"}, "Internal Users - Base", JoinKind.Inner),
				    #"Removed Columns" = Table.RemoveColumns(#"Merged Queries1",{"Manager ID", "Internal Users - Base"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

