table Months
	isHidden
	lineageTag: 5bab7d17-5241-44ab-a34f-4729ee803709

	measure 'Selected Months' = SELECTEDVALUE('Months'[month], 2)
		formatString: 0
		isHidden
		lineageTag: bc76478d-9cac-492f-9b3b-397ef950dfe0

	column month
		isHidden
		formatString: 0
		lineageTag: 07fc8977-12f3-4711-a0aa-73d0cd53b26b
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition Months = calculated
		mode: import
		source = GENERATESERIES(1, 12, 1)

	annotation PBI_Id = c1d03ce227a845169d334d9f6695d2d3

