table Platforms
	lineageTag: fb83567c-936c-4cdf-8e99-e50855b05410

	column Platform
		dataType: string
		lineageTag: 45510a5b-e23e-45b9-8128-f1af1d06b146
		summarizeBy: none
		sourceColumn: Platform
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3602f615-ccbf-4aba-a381-e2b1d3945b3a
		summarizeBy: sum
		sourceColumn: Order

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Platforms = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wckktzi7JL1DSUTJQitWJVgpPTQKyDcFs3/ykzJxUINcIiavgWABSbawUGwsA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Platform = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Platform", type text}, {"Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

