table 'Survey Latest'
	lineageTag: ffd172ac-b2a4-4899-8781-544b9c765629

	measure 'NPS Detractors Latest' =
			
			CALCULATE(
			    [Survey Respondents Latest],
			    KEEPFILTERS('Survey Questions'[Order] = 5),
			    KEEPFILTERS('Answers'[Feedback] <= 6)
			)
		formatString: #,0
		isHidden
		lineageTag: db810b10-9cf7-4397-88f7-0d426768cc2a

	measure 'Survey Financial Gains Latest' = CALCULATE(SUM('Survey Latest'[Feedback]), KEEPFILTERS('Survey Questions'[Order] = 4), KEEPFILTERS('Answers'[Feedback] >= 0))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		isHidden
		lineageTag: c3db4ea5-e431-4dc1-b511-4d542eae4153

	measure 'NPS Promoters Latest' =
			
			CALCULATE(
			    [Survey Respondents Latest],
			    KEEPFILTERS('Survey Questions'[Order] = 5),
			    KEEPFILTERS('Answers'[Feedback] >= 9)
			)
		formatString: #,0
		isHidden
		lineageTag: ddfd99ac-62c9-4ca3-817b-3bc9ca7ae6e4

	measure 'Survey Respondents Latest' = DISTINCTCOUNT('Survey Latest'[User Key])
		formatString: #,0
		isHidden
		lineageTag: f2db7d79-e8ed-4c0d-9962-27a06da58c0d

	measure 'NPS Latest' =
			
			VAR _respondents = [Survey Respondents Latest]
			VAR PromoterPct = DIVIDE([NPS Promoters Latest], _respondents, 0)
			VAR DetractorPct = DIVIDE([NPS Detractors Latest], _respondents, 0)
			RETURN
			(PromoterPct - DetractorPct) * 100
		formatString: 0.00
		isHidden
		lineageTag: 6d9ed30a-0061-4e30-8e14-c0ba6040b4ba

	measure 'Survey Avg Financial Gains Latest' = CALCULATE(AVERAGE('Survey Latest'[Feedback]), KEEPFILTERS('Survey Questions'[Order] = 4), KEEPFILTERS('Answers'[Feedback] >= 0))
		isHidden
		lineageTag: db72a58e-0223-46bf-9502-6068d41257f4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Survey Time Saving (Hours) Latest' = CALCULATE(SUM('Survey Latest'[Feedback]), KEEPFILTERS('Survey Questions'[Order] = 2), KEEPFILTERS('Answers'[Feedback] >= 0))
		isHidden
		lineageTag: 38b263d2-5401-47a3-9122-8e63a7c23d1a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'User Key'
		isHidden
		lineageTag: d132cd58-6977-4cd5-9c36-e773f3a4ff7a
		summarizeBy: none
		isNameInferred
		sourceColumn: Survey[User Key]

		annotation SummarizationSetBy = Automatic

	column 'Report Key'
		isHidden
		lineageTag: aa9c6c21-a833-422e-91d7-76b1006a6c49
		summarizeBy: none
		isNameInferred
		sourceColumn: Survey[Report Key]

		annotation SummarizationSetBy = Automatic

	column LastCreatedOn
		isHidden
		formatString: General Date
		lineageTag: 4860d7c0-cb63-4806-bb02-93826e8f37b4
		summarizeBy: none
		isNameInferred
		sourceColumn: [LastCreatedOn]

		annotation SummarizationSetBy = Automatic

	column 'Question Key'
		isHidden
		lineageTag: f6cc52f3-65f3-4e6a-a544-2a8045f59665
		summarizeBy: none
		isNameInferred
		sourceColumn: Survey[Question Key]

		annotation SummarizationSetBy = Automatic

	column Answer
		isHidden
		lineageTag: c3212edb-f768-4241-af5f-4c0587b36e11
		summarizeBy: none
		isNameInferred
		sourceColumn: [Answer]
		sortByColumn: Feedback

		annotation SummarizationSetBy = Automatic

	column Date
		isHidden
		formatString: yyyy-mm-dd
		lineageTag: c46a22d5-c8b3-4d08-9426-3abd551adba9
		summarizeBy: none
		isNameInferred
		sourceColumn: [Date]

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Feedback
		isHidden
		formatString: 0
		lineageTag: 8b589179-d5b9-4724-ae13-65aa06c2abf0
		summarizeBy: none
		isNameInferred
		sourceColumn: [Feedback]

		annotation SummarizationSetBy = Automatic

	partition 'Survey Latest' = calculated
		mode: import
		source =
				
				VAR LatestResponses =
				    ADDCOLUMNS(
				        SUMMARIZE(
				            Survey,
				            Survey[User Key],
				            Survey[Report Key],
				            Survey[Question Key]
				        ),
				        "LastCreatedOn",
				            MAXX(
				                FILTER(
				                    Survey,
				                    Survey[User Key] = EARLIER(Survey[User Key]) &&
				                    Survey[Report Key] = EARLIER(Survey[Report Key]) &&
				                    Survey[Question Key] = EARLIER(Survey[Question Key])
				                ),
				                Survey[Created On]
				            )
				    )
				RETURN
				    ADDCOLUMNS(
				        LatestResponses,
				        "Feedback",
				            CALCULATE(
				                MAX(Survey[Feedback]),
				                TREATAS(
				                    ROW(
				                        "User Key", [User Key],
				                        "Report Key", [Report Key],
				                        "Question Key", [Question Key],
				                        "Created On", [LastCreatedOn]
				                    ),
				                    Survey[User Key],
				                    Survey[Report Key],
				                    Survey[Question Key],
				                    Survey[Created On]
				                )
				            ),
				        "Answer",
				            CALCULATE(
				                MAX(Survey[Answer]),
				                TREATAS(
				                    ROW(
				                        "User Key", [User Key],
				                        "Report Key", [Report Key],
				                        "Question Key", [Question Key],
				                        "Created On", [LastCreatedOn]
				                    ),
				                    Survey[User Key],
				                    Survey[Report Key],
				                    Survey[Question Key],
				                    Survey[Created On]
				                )
				            ),
				        "Date",
				            DATEVALUE([LastCreatedOn]
				    )
				)

	annotation PBI_Id = 5b104cde29d74561b1ae0b1f99e35a2f

