table Calendar
	lineageTag: 9e88e2d1-433a-4501-8112-4d8a1b2a99d3
	dataCategory: Time

	measure 'Active Days' = DISTINCTCOUNT('Events'[Date])
		formatString: #,0
		lineageTag: 9db0b194-a454-4b02-9767-46f2a878ac13

	measure 'Monitored days' = COUNTROWS('Calendar')
		formatString: #,0
		lineageTag: 849fb423-b3b5-4002-9399-80704808c8a8

	column Date
		isKey
		formatString: dd-mmm-yy
		lineageTag: e0412f9b-e97c-4471-a048-500706e57d1f
		summarizeBy: none
		isNameInferred
		sourceColumn: [Date]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column Year = YEAR('Calendar'[Date])
		formatString: 0
		lineageTag: 12ea734a-ef5c-4ab6-8293-6cef4b7f593f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Month Val' = MONTH('Calendar'[Date])
		isHidden
		formatString: 0
		lineageTag: fff1300a-e11c-44fc-bc01-226b1559f11d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Month = FORMAT('Calendar'[Date], "MMM")
		lineageTag: 34a333f0-9c61-49ee-865d-66c164039f11
		summarizeBy: none
		sortByColumn: 'Month Val'

		annotation SummarizationSetBy = Automatic

	column 'Year Month Val' = FORMAT('Calendar'[Date], "YYYY-MM")
		isHidden
		lineageTag: de9b823d-7ef5-474d-b9cc-6d3d73f2347f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Year Month' = FORMAT('Calendar'[Date], "MMM YYYY")
		lineageTag: 40acd859-c6c2-4c19-a7c9-9491f3d08d0f
		summarizeBy: none
		sortByColumn: 'Year Month Val'

		annotation SummarizationSetBy = Automatic

	column Day = DAY('Calendar'[Date])
		formatString: 0
		lineageTag: b980fa19-caca-4947-8a45-2da8da4910ad
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Day of Week Num' = WEEKDAY('Calendar'[Date])
		formatString: 0
		lineageTag: dff60bfb-02e6-4985-8a93-20d8f44cd40d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Day of Week' = FORMAT('Calendar'[Date], "DDD")
		lineageTag: cd7befee-31af-41a1-8ff2-b777834d8e00
		summarizeBy: none
		sortByColumn: 'Day of Week Num'

		annotation SummarizationSetBy = Automatic

	column Week =
			
			VAR _num = WEEKNUM('Calendar'[Date])
			VAR _num_str = IF(_num < 10, "0" & _num, _num)
			RETURN
			"W" & _num_str
		lineageTag: 7696097f-bd00-4f00-a06d-c3bd363687b4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Week Start' =
			
			VAR current_week = [Week]
			VAR current_year = [Year]
			RETURN CALCULATE (
			    MIN('Calendar'[Date]),
			    FILTER(
			        'Calendar',
			        'Calendar'[Week] = current_week &&
			            'Calendar'[Year] = current_year
			    )
			)
		formatString: yyyy-mm-dd
		lineageTag: b2ff94db-e370-414a-be62-2ff55c369ef3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Quarter = "Q" & QUARTER('Calendar'[Date])
		lineageTag: 8aaabef2-c30f-496c-a4fa-ffc614a205d9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Quarter Year Val' = 'Calendar'[Year] & "-" & 'Calendar'[Quarter]
		isHidden
		lineageTag: 4fec5bf6-c5a6-468a-94ca-0764578aa4ad
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Quarter Year' = 'Calendar'[Quarter] & " " & 'Calendar'[Year]
		lineageTag: 30c1d79e-e48c-4240-9985-4a76b5f47c2c
		summarizeBy: none
		sortByColumn: 'Quarter Year Val'

		annotation SummarizationSetBy = Automatic

	column 'Year Week' = 'Calendar'[Year] & "-" & 'Calendar'[Week]
		lineageTag: 236fb54d-a044-49aa-8523-3b5b3a074856
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Week Num' = WEEKNUM('Calendar'[Date])
		formatString: 0
		lineageTag: 073dc967-f45a-48de-873e-5ec1ca81efc0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 3ace2f10-cf59-46d2-885d-23b180e92eec

		level Year
			lineageTag: 106e90f5-93b4-444c-96c9-75cc07212887
			column: Year

		level Quarter
			lineageTag: d7666d59-11e6-4dd8-94c2-ff98510225a5
			column: Quarter

		level Month
			lineageTag: a5e49f1e-a28c-4394-8161-c03346950c7e
			column: Month

		level Day
			lineageTag: 699abafb-0188-401d-8ac3-adabb72327f7
			column: Day

	partition Calendar = calculated
		mode: import
		source = CALENDAR(MIN(MIN('Events'[Date]), MIN('Report Scans'[Date Since])), TODAY())

	annotation PBI_Id = 4e4686d0cea04af2b2aeb26b5523463d

