table Events
	lineageTag: 9ff77e11-8607-4bbd-8658-7a7e02f97901

	measure 'Bookmark Clicks' = CALCULATE(COUNTROWS(Events), 'Event Types'[Event Type] = "Bookmark")
		formatString: #,0
		lineageTag: 99623a79-d06e-4725-84b3-9832732d1296

	measure 'Unique Bookmarks Clicked' = DISTINCTCOUNT(Events[Bookmark])
		formatString: #,0
		lineageTag: cec2a476-ed4f-4edc-95d0-24d9e92557ab

	measure 'Link Clicks' = CALCULATE(COUNTROWS(Events), KEEPFILTERS('Event Types'[Event Type] = "Link"))
		formatString: #,0
		lineageTag: ee8d96f6-9671-4b81-b095-8d5929f81dcb

	measure 'Unique Links Clicked' = DISTINCTCOUNT(Events[Link])
		formatString: #,0
		lineageTag: 1828682d-bef0-4485-a280-27996d826575

	measure Drillthroughs = CALCULATE(COUNTROWS(Events), KEEPFILTERS('Event Types'[Event Type] = "Drillthru"))
		formatString: #,0
		lineageTag: fca2cea0-ff1f-4a5d-b240-d59688ee900a

	column 'User Key'
		dataType: string
		isHidden
		lineageTag: 247637dc-f2b2-467d-b7a1-3b56e0021df7
		summarizeBy: none
		sourceColumn: User Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Page Index'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9e8e75aa-126f-4576-9c11-404cacc9ba52
		summarizeBy: none
		sourceColumn: Page Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Event Type'
		dataType: string
		isHidden
		lineageTag: 78a0e520-3c2d-4656-9ac5-e54fbdaf413d
		summarizeBy: none
		sourceColumn: Event Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Link
		dataType: string
		isHidden
		lineageTag: 9269fa6f-3662-4f8a-b0e8-709b50293da8
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: Link

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Bookmark
		dataType: string
		isHidden
		lineageTag: f79f389a-623f-4c33-90e7-c9e4a91d42db
		summarizeBy: none
		sourceColumn: Bookmark

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Visual Type'
		dataType: string
		isHidden
		lineageTag: 63275137-4d33-49e4-bb10-7df31ff41cc0
		summarizeBy: none
		sourceColumn: Visual Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Visual Name'
		dataType: string
		isHidden
		lineageTag: 986981a8-94d4-4d67-a833-1ae6af5261b0
		summarizeBy: none
		sourceColumn: Visual Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Filtered Column'
		dataType: string
		isHidden
		lineageTag: 56c8d503-3a99-42b5-b720-7fcea1e3d9d4
		summarizeBy: none
		sourceColumn: Filtered Column

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Filtered Values'
		dataType: string
		isHidden
		lineageTag: 95da2cd7-c31e-4660-8ec7-fa79ce874ba3
		summarizeBy: none
		sourceColumn: Filtered Values

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Filtered Distinct Count'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 09895014-72a0-4d4b-bf2d-f59c9093db8b
		summarizeBy: sum
		sourceColumn: Filtered Distinct Count

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Username
		dataType: string
		isHidden
		lineageTag: 349a22c8-4801-4a68-bff5-5ee5baa65782
		summarizeBy: none
		sourceColumn: Username

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Client IP'
		dataType: string
		isHidden
		lineageTag: b6b4a9fb-cb9c-4cde-955d-4e4192547054
		summarizeBy: none
		sourceColumn: Client IP

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column User-Agent
		dataType: string
		isHidden
		lineageTag: ea42be79-eaf4-4062-bf6f-074498855509
		summarizeBy: none
		sourceColumn: User-Agent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		lineageTag: e2fa6d76-44eb-4a6d-8925-feedf1540b04
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Time
		dataType: dateTime
		isHidden
		formatString: Long Time
		lineageTag: 0de5307d-0f76-41cb-95a7-259c29eec843
		summarizeBy: none
		sourceColumn: Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Report Page Key'
		dataType: string
		isHidden
		lineageTag: a12670fd-cfba-4cff-8888-cbf5aa58fc9a
		summarizeBy: none
		sourceColumn: Report Page Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Platform
		dataType: string
		lineageTag: 65a49d6d-e3c2-437a-a5d2-9077ea83b879
		summarizeBy: none
		sourceColumn: Platform

		annotation SummarizationSetBy = Automatic

	column Feedback
		dataType: string
		lineageTag: 42b0756e-69e2-42b4-a7fc-6afb99bc4247
		summarizeBy: none
		sourceColumn: Feedback

		annotation SummarizationSetBy = Automatic

	column 'Report Key'
		dataType: string
		isHidden
		lineageTag: 084c646f-55d0-4ba8-b766-1af1cdd93c48
		summarizeBy: none
		sourceColumn: Report Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Visual ID'
		dataType: string
		isHidden
		lineageTag: 6de5c68d-1293-490a-9900-329431458eb7
		summarizeBy: none
		sourceColumn: Visual ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Created On'
		dataType: dateTime
		formatString: General Date
		lineageTag: 5dce7d12-9e42-4f9e-b69a-3331f3f89ec9
		summarizeBy: none
		sourceColumn: Created On

		annotation SummarizationSetBy = Automatic

	partition Events = m
		mode: import
		source =
				let
				    Source = #"Events - Base"
				in
				    Source

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

