table 'Event Types'
	lineageTag: 6a785350-e7dc-4a07-8a0b-fa4c48b338ae

	column 'Event Type'
		dataType: string
		lineageTag: 11a9b16a-cb85-4136-97e3-e94fc68fd47e
		summarizeBy: none
		sourceColumn: Event Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data Event'
		dataType: string
		lineageTag: 1d651338-65a0-4eae-930b-8d3a82e670c4
		summarizeBy: none
		sourceColumn: Data Event

		annotation SummarizationSetBy = Automatic

	partition 'Event Types' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WcsvMKUktUtJRMlSK1YlWCk7NK04F8gzAvIDEdATHLTU1JSkxORsu4JOZh+A45edn5yYWIQRcijJzckoyikrhZofk5+eUZBYg7MrJTEayOiyzyhkokg0XCPIJhrBjAQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Event Type" = _t, #"Data Event" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Event Type", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

