table 'Fabric Operations'
	lineageTag: 7c2703f8-3db6-4e2d-9d6f-9f758d092358

	column Notes
		dataType: string
		lineageTag: 3138cdbe-1033-4d71-a535-8beec659b274
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	column Activity
		dataType: string
		lineageTag: cb3a10ac-840a-4924-9cdf-4a37ccccd293
		summarizeBy: none
		sourceColumn: Activity

		annotation SummarizationSetBy = Automatic

	column 'Activity Key'
		dataType: string
		isHidden
		lineageTag: 0e8be886-934f-4eb9-8a6c-6818a5651eab
		summarizeBy: none
		sourceColumn: Activity Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: 20422b35-c52d-43d5-9f14-257c45407e51
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: string
		lineageTag: 24643ae2-f942-4756-ae6c-43c79ab9dc49
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition 'Fabric Operations' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("zX1fc9s4su9XYeVppiqblUSKkvfNsTNZn00mXsuZuVXnngdaom3eyKJWlJzxfvqL/gOgGwApObO36takaix09w8giQYajUbjv//7zfldu9tny3b7kt2t27us3da7at+0mzdviXZhSO8Nxfz+sqk/Vd9qz/MuW+zbbZdV2bberJrNQwbc2XsF9DarNqtsXVfPNXCu6m7fbJBCNX5v9o/Zv+tda3g2D+ZvYL8/rNfZU72vVtW+emfqHr/5n7emtctlvd0bjqzZPDd7Qtm3Wf3Hvt5tqnUG7Fn3WO1qaD9yf2DapSEtFOVUnAnVvVpl56unZpNd17uuBa7f2923blst6wwAuw6QVytksjyOxXGYf7kH3O2b+2q5z27b7LrZ1utmUzMKU25bUW7+FU72wx/mFTdP9Waf3Rw2JOXLqMj8mzqBz+2qXme/mZbx912tsMiXmH+lY7+tN5XB/kf9Qrz0m36afzPP2Ky50f4vLMyazrzJ7vGurXarzDxMY172y9vs+2OzfATiQ72BXlKvMvP+qxV2oeemO1Rr01W6bG8wOvguVXbdfq932fur7NLimXrmrgnfzWtet9XKfE/DvKeWt7tsWZl3b+o0zNAPNl1z16zN73NoC372y5dN9dQsudXVUaTsftc+4ZcHri77+wFU4yxuyTO9VYnT34oF9EHfiG5bL5v7ZulA2vuepoFqjFTl1CF3rf0SrgfemKLfmgq75/m24coikfHYwpnP4l77fbtemb8q0c9/wSLXr39tzThy2O1M31u/ZIeuhi80nqTAHnbtYWvU++nOPB6BfYSiz64ERHMhSvrYHnamnaY/eCTTeb5X3EFBw4nntv3oCABVCCin47uamK3mUPGNLwXJqZA0SvhNjRIa4ZMh37Y9OKXAMe9ml3qKbLk+dEaa4L4ars49yIUjpd/z7BX4+DZly5NVXUomqMJqGwyBH+u9G7u67P0LVnm1QjhDN2RHJSLSAOVMoFT7fbV85M97v26/Z92+3VUPNfSz9mAUzzyF6+fUcVnkkiUWJHBO/LftreVOvqYJq4r5Pi//rrOrjRlEl2ZMxGetsRIiXW2Q4MtBeJwWvqm3Zp6MZF0xiE6kqNCEXVrWFHx0Q+P3xxr0HV9xV69reOO2EY1tBIyfjAajVVc/mddgBpAnHPMN2/6xNqW758ZoEMyw3QEVFybaFzcOdzAlEiCMC3dt+w1an/e0Xtfin2L1/sWqwfl2u26W1qIIHgoeqTONM6wwB6IlINoJVbPmbsHAAHth+Y0G4K83n6A+LH8Pxb+YUipMmCm/7xp8OEYwoykOKIhUARZ2NFMz1AJjrXmbrsq77CfxozOvev3yM7RtGrfNwNyRsSSa9qo2/UhDStkQi3LPczGWQke+bX+hokRjvm5pNrPCd7WtF2dfwMp+uvxl8TPYYpOZrW/d1DBdLR+rzQMOzK672T5CLVi/XCCLMWag/P3VZ9thqFs/meZ0Csg8eP1HA6biA4G+y24fjcXQLo1Sd9h96meYkDYvWb1q9mBNPFWr2r4/ashP9R9/y77Dizbgl+f/y8w5VXfY1W8N7wbGmV29xjfQPTbb7m1W75fv8I3O1RN2MGWT8ZKtqzsDLEdXg/5kZBae6RPwsDAPADzsdV3zsBF2ozH7ztdPyvRDFsdx2xq6tgDzkcCqrc1CePi1VrX5mi9oGG4HgAVqcrDMebzDETczLDWMB9kHYzHv2g3AAypSLTFF4+7sCMaU2Dk06E75RNbDkzzMMbtq+/jPT1nFM4lDXCALk309XvIBSP9aS8k8F5UMzDgOrm+K4W/A49IBdKXZ8Jy73NUr84QNmK+G8NAgnOF5b1g+NvsLT2cCCbueHqHAu6oAKNvu2udmRRM7lSzbzcZMBjSy5jQYQUX9IzQ2yhlGwBsYSnkpUZ7aTfMNRmjZ273t0DHGZ2a7bS8VDfBopHi/qzbmA3057PG74muhMlN0tZEFWeuYQKVl37brh9TygefITf1dCBgO8y6BLpYc/NZqHtmMhOnx5jV/MyXwVu+oGXdm3sdVCfReUb5/rPYRDPC0u+bBtNvVjj2bhpELI8lGxpPpktn7ar98NGQqt8W2FOTOQjljhBg7494YnFrQlPtiWB2OpOT14W7ddI+ByhKRaSlStmW5WhGLscQ268sNdNlzr2NEYYIoB9mJlF1sq923TJsGREKKJoB0rqSNZqOhYfp1Z55ttW2NCZHBlPbYGg0K3q9hd9yW2fFqVhxM1w5nAYOPq6i2Fd2BzLvselc/N4bPdB+zgjSiAmNV31eHtbFoqh1j/fTFTrbI/TfmviTG3y0ftgdmoKKQj+zowbNpOX5ZUyXptOHr1gyLKzPNnnfkx/AolseynHeWAfBKifcEYyAonGvRnWrRZ6JHDYvM2R4g1C1+kVD5TFQuBzY3fu8SWgEErRasiGherOKFUQWPC2MWcfCYiC/BjMym3a1dlRZnw0hyoYrmbQjqx8ivnVvrTkdp1GD49iN+hwbH/ny9vlBlgDVWWM5v0e1NA1xrLrh4waUgOEkL4qRUofXAI8HXrXlMB4HPcS7pAJYrsNiCgpntmAnF0ozIGvFYG2t5sWx39RK8Ss7/gARX7op/q3fNfQNupMea3ReZUcWnpgPHip1hOysHFU1FRSzB9jQsrdi+RzLVAmb1l12/kxRZzTrnHtuwrNZrN9c/VrI1UI35ZZr0ROsgcgPBRCTcstPStw9mS544r+zMaglUbqdXEGRlWtfV5rDNDpsDznHG4mh3u8MWtPEePW64LrIa1v3vw2g0mVlFw6mdIayu+ZI/AzplJV23m9r6FPEH/w0srH3Gaj7sH4UdCawtlYki869kzWqfnswkrtihJGAeS2Zjm/MLxd/GVBK/mIo2ysYZmsM+TrHmXRKIk9sjGtgM5cS2YbuuQUrDY2/c1f861B3VRh5GudxiZuqbN8Rqym/NGvsbqcGm3YN3kaajriY/i1nvGROz5sUVehOoFm9GwWc1pqnpkNhSVnEagOTrwgL/viS9z6g7/sIIBZqvljv2tRWyMWSW9Q2j2BOdE888t28leBHSrguoYxrXUYm52bydHpOBHA2bnkodwvlmNWitBK0zCLERohv3XTYutkpS7UqYKnEzQ7slaBlYMGVp35bpVPvUponpEe4HvQ3gjHZOblvJBcg8jrXbRpsEfmcA9qHkTgFIzZNSzgMHItJnV9qxZvvipxvmk7/Nv9nIs9rpYXDbDBsBisCWAjp3eO0ebI+h685oRegZNd8TPKhGlR/BL6ipoBEzHsxQdeEjQ980Gr17sX4v9/Wgvchmet8/gQM+p6QC3ETCSasfS7S5P8slczRBYbGenlKsNFaoxe/JwwXB8aKN1pP4UgrZMDO7HFaZt8gyeO7sH7Akv672j65ZyOfZgAuYmAdgp0OwfTgsW0pZoGawTWlMBCdnty5lGa920zuWs1mICStMhccFt2bZ+lDv9BLarVTF0I97TlIRZ/OwDlikvn/J/nlowELjpvgaDfn9CxItDVDOFEpj1Mp05ZewszhC0F9CgT/fZVYO0fea+Ug2UiyZM7HLQ1RBjGhuvwh83sHieq609Zfqbmemqyv0A+3RP6GHSmRzJZYPdvdwY891EQZqJJCYfqFipde0p+cQ3M+rzQqmQnLSAsltSiqXC+Ap1edFT8Z7ShmsFRy63m9iEkAUKQi1Ha0Ago3puVLGj61Rjt+q9cHopfn90O4aMmEJwVCRqGgAorTy743pL7vl44uAcxiO6MAYYpaGAJszFuZSkFOK5d0a7L2ncm8TOON4ftYjp7+pl7Tl5t/ZKC27MAb1fnnYx9KWAruejDFOY9xWd6mG22KQVH0QEPE9+88ERbYE+FUf+4yufDNk72AzvXYeISfNDEyPyBC+wqLOYIOtKBzxnhjc6Or+YD79pt5Db08o0lmRatRvv9ZRQ1TZa2pQHftzvTeqvTBjLv2VeG7LQX+IKkmAHhD/hqG79vJnqvc71380olnKkaFuI7z9Z0orvuweMrJkqcD8pp/AqfTA2Y+JedXSwqn1TGkEGXc0x7te6DCICkRJewPhFUo3vOfBqa43nyxNkhBinIb4ram/x9JcioJKMxZ2HdP3xS1D+MG7fbVZVbiw9mshwhBffTzKdW20W2z0ZrNstubVX+/aezkIMYdj8HREUwpxW5sFLZqOZolxbZaiptM7IEs0tJCUFLTLblNyLKpIz1Y9rRiPpmFbjT1tbADaF80+td5P7RqMHMQg6JGjc+/ADgQG283esMLgtpHUtxWHQB0z1n9Drj57fTxSihaLR/xK3QasDcuvlAtsz2CqEHNHYgl0Dfal+SaWC1aZ+127XuOUNB4rpZNLVGXostGVCPE7JjkeK53EtZaILLg+7GH5NhhVQKIdG0EUPrmDBeW6WlIohdvYA80z/WFXgyNjb4wxQ97VIgABu8F4EjbJt+Q/0QSqJA8qMcb6ukEXEVW1/PaJfiYXruC34qiFu+zuhX2UL1ADhW7gVyXYq8uONsyW7ZOZYo0tACxEA3lqTxG1RzTlxMfm0IuaHWvoN+uyLfexKqpTqTt8kqrZCBvpQpQcrV5sOG4y5sZK1CTq1hXxmuaUSpw4tV/pNnqmu5eOnOhsuZuyhS06/REIfR6iK9hTAEGIsNQokQpEsz4Q1IVvsPbemnV19l+LL7/2rBR6V+I/XMt4ooYbo0IH3OIgUet1bddi5fBlR7sg0Bh2tSp651G6JMx4ogag7nB3rw31hShBfjU6mFdgbER2vtOcZEp+oQJkV3oeWpfYIvuizFr5D98vfyPWX4kTno9f/7Viy/5+e3tNomirDtWA7SnUHOcccJUw/5ztN55M09zKyceuBeXmG0/KPkm/WeF8Evfifc3ScsZeatbwebrlrtkqK+ADkBaaglDzNNRgHOZwT7fIZ4PIIQxL5aMeKQi69TL8CyXGaQnvLRVGs5WZpGVO8b5LJ9GgD36c56fUEmJaYd0HRVg5W8PPamUfLOjH+bRP3O0fMpCCsNLlUel4LWBlZ4FswkTc9Ow+9BmMg1sNtt55X5v31pLWy1Retjqq/L7CyrfwujvjeQyzVlmvM9OobzXFinERWBhx7T34VyRziyhcWTEKK2t3D9Wm+Td2L/Myl0bnzIukV/sGnF5dvdt/UUwfK7BQX65oYkXYcQgbOdqPfBfpdT/loxRa0dLhfjyghsGDYxtLI5/VbvUZsPN/H4xden7pN76/1XJZQ3LUk87PL2nmu2UmxC8G8b/c38Oa8vf6DpZgXViNhP/9/ELDpyPfOd7l8tN1drW5b02R+ZP/Qnrp6DeHNXhmKCLFFMDvzz5yZszRJo7162bVek7+hYykFnYGyZ6aB1rzydMBcWSh5f/M7P60QBRj2POsZ7peGchQQey/qOTa086ZlAbl4JMk6K5+ap/7YG8csQeYNOOyho1sFefKURsyFIm4RH8lFhWKNOYQlX7EfiCLkCsEv2vFYmoba8wxJ8xtA14y+P1gd8/3sLryFVsmckoviOwFHJ9HW8VoaDpzHAqziz0bKhEFyF0q7taYJhvFS0X+fYacYw4PUeUUptGxDzm74XBp+HBc9OU7LZPCiohsBcx3pALN/upaxhwkwuI9WzFETW/FsOTAVsyYo0xsHeExO0aPT9qNOdiEBY9t4hBb/yYOw5yyiTMulao5zz79jnZxKETRkNTRMg+mtAx3PC5IuXkjxax01mgqEgtwMAPSHRnB8ggMYs4OHQ6xnQIhgi1H6SKSvq12D7VtyYWMgfZAxEMbO5IDIafDkImHE3D62coIKrHT5HGSO03jcpZGiUWtwDwU0NU4YNWP0bxPdEAsD517M9WTe7a/iNq3/TWejdMYvNMVSPv9r/FM9b9oA4zKExtg41neI6j1IbkDNp4VaWG7TxXIiu2r8Ux1KbV/xVJ6/2o8Ux1nYAOLOHo3sNwQ8Z/YwBrPZqlW8W6Vaokqs1WcUoPquUM7WFxdtINlqzy2gzWeqc4fHn1meH36OYqF+FwtH8G2+FRXOwx2Jxh3slfaR+O5UpnUnhmREntm5Enq3zMbz5UqpbegiJjcgooezC9XH51awllthFjBUSs85fAW/bWOxU7T9ly+EHkL7UVuXEF3MKvgyQno9PA4FEgxnk/SD8JbXsEzcOlA858NR/YTuK/fZo9mwfNUbfF0IzicjRn3s3wqrF+NEAP7adyScD+NBU/cT5sXurae/bTYDO7ZWNPG8Hx6EvoxUIumhqSefTKiJnfrBgRfsVunrRIFtvW7dXM1UN3Kh1Q/XBKC6hVpCGQT9j5yuScFwXiuhjS5qcb2XbDNNlfjkg+GNGYfp5eQ1p+j64P7AHSmxhu1/8bf+8/sv52pEQfPR+B5MLNOhYGQ0wE8m0bDzspd+4dfQgHvZ8dKc6xp/ifHh/iTGP/QQWdxX6rrh/8KnO4zdDG6UnPwJ6UWGp1bach14zpcw3RiERMsnk5DHp+pcYD39ehX/9Ye0aHv8ss206nbVjlTur9sN/fNwwFGyKU6YsgWXrO/5mi4iwRZiqvIuWV0ENHlpTh03E3KoB1u24xXw8Mbaf4Z9Q7UmVJwvb/Fa5oj+1u9yPMQWUEOHeMY/iBKrQcPsbJ2BodYI8nEIdbJSOm83DJiUL1lNBkpLSb9YnMpe57YITWpZ6hiNO91zxMeyUNFm4yUGp+0yUS8RzeZ7LLhVZtMk5FSfJcwxc8dKv8KsUVzWJUSnIyKEFqlTQnG6zjZSp/gZDRNzwiXsV8orueom2kQD0/zj6QOix0V2EqvhTF04X6j1CwtJTfoiBhs0E1G8z5Jtx9nBeUG3WR0lpZLbtARV88G3WQ8SkOFWW6k/2Q40c1kPE5DDu758fg8uOc3GU9OQu6BsyD5IEgobKWKHineKhQeBCsxTUs8aQvab4tNxj3dbyPdBN47MBn3dDy3NUkUlX5l3NPl5MZbsPawkj2d7oRNTd+Jj21qTiY9/TGoZdd+70LgGyrzAdoYcANrr+tD92jj8rvsL/5PfkFGMDu/vsq+Vx0eSqR+POnpx9H+qmqFfY6eriq3607aMIwWGrYC3Y2rV+y18fd9xV4bJhypDpBdpH4G7+eSzsfdtftHXiYYU5gqVEF7jV00wGfoORLGC2RZ32Si1W3wwE78OCrE70daKgEmE63Ix3dLifPIbulkorWdx1HyGojzzfB6hsYO6W4OPbyTiR4h0vuj1twP9kcnEz1UDOX8Ip6htF+TiR4+KOWZerjTRnHKjMaguR4tgu8i5m+MNEQbRn4fr0251vXEIW3oGsdOafttQMTUQ0C3qbZmZUo7+XjkWZxW9bm9uDcz85u+9FcrZ4I7XBzuVjXM8HdECQeqSW4HDegHCVcgFMeJECd5IcXoFLwfueE5fjlssN8t2BsKjHCMxbzhFCnG2D+aqfPhUQIpez+fiibYM522E4MXis1WIMddObe6toeTs7S1zv0EFqq7bNGuD85eAibNY1gEByLOHOLuCZrAZ9opb40ZIzC6Ft0tysphdud6uqg2GKerbB3IKQdg29a8H9gWXTboZoWe4yoxbyBZx4QjVS6bzh4VxkB/Oi3mS6EwLHOcP3o4eeWh9PnkewZGO5uDXbDeZ3Rn9s3zImCxoxcTZdaZcDTLZft9g0k79M6OLQ32dSYcrAJ0XN/0baAyvWcL1UoPbKJOOEjF8SYd4kxMuMR59dLrEp9wHIvDdzllsk/tg8C2GWWoFCULJZm2IZmorEgbaeIFP/wBZBXNaI/qs2uBOGxYgRV9A6nyzJxC6fpIh95tt/s/wDh6t13dk88D8wxRHgCsn/V5124Tu2KmNLEnNrExLYGQ8xsoMek7sDEuWtDthkk5sRc24RCVD2A1uey2xrpqd6aTU98AmiVpCgBwOAoC8JGdy1ou4IBCBF2OwmMvfDRPUNyqQYswZj8tX1Ct5CYcw4JNZG81/C3+/CG3NaXOw6hjyIeHKUvsMp+GUPRl445Z0pM94dAYbIFPahA/taMlvl0hIJoVbKqL56ISn81jwhEuyB7nAxLvrWOEMLuQbkFgMwwj4vmLGj8iNqV0TQmCk4PvBxwXZFlZp6r5/7Y2/dmNzRxJE4Itgcnl3fBhVhZVkq8lNe1x4FCYsBbpgAGa/MY9QGc9QBwQFr8AFwwWPnk5SkJxYtIYiPQ4hhkPwChRKzBJCgTzavpBIIgq7splfgpiat1vcY+u+svilCq28uUI7PilTU+A0xhWkjv/BsbxvxoDBf6fna/NF65XV5uvm/0OViEr7Pd/GN0R/sh+LhfIRLiYgeRV0BOOjPmwWe5eMJNQuCORTL/lbAiW03seiDsfwD10KtI4Xp9ZWCpIoLM6wZoWPBqXTfWwaTucFIQBYOmCLKgAxEE4SSBc9adRLAkhxhpiCaslY1RtjXlf6ySHylm/ElUBIV3ThUETlD+DPuGgH4clbeCseqggCjy7/Hy7IAouElgnbMPg9B8JnBM/Occv19vrmPsVFUw4rsjYcut2V4ts0VyitYkDicjyc3vgwXqLqEyMF1ocUWQx3HRkU2CiP6rz9iWXf7DFiFFKDOnYpKK4pAsyoU04Iig2c4WvnoiBr54DfWJB8CFQfl9KXIN2LiQ8q/aRtWyxznqweFZJo6EhZEWYkx1ftkMjVU0jHMMTVwXGk5YTZgxH55iBHtNY98ROMDkZPDEkemr0hFiP1gwnj38qaGOW+pfmHlKxyJXjhMN2fqkhQ6MPNQgDgtAG2/+ZuIMJB+j8AokXH3sSmBIxmcCU5dIJTCccj/PLGjzjQZ5sLDyWJhs3J9FZjuMCR+CYZROYSbynQb/EBgdH1oSpUBbmvy/mnXd7HcWqHX+LxRdgiXycHAJjTV727mR0ciL7PTvPLmyQ/e3AEY7ojAVizzX258N637h1e/bh6c50txAVmSwPsijIMw1p1m11vQl8fQtZCFIc4uLtetdV022IquUolgSAM24X54vokIvL/Fyp98IxK3j3wXrtwjUx3pODq8iv5i4h+IgpOpkR+Cyb4XJMCJ0raDc0dw5EFaFIIUTEQQhMxylDylDe+QY5W6cIJJtwMEmINAASApQewC75ufO9f8EGZVerKMJJXBJBzO/ReXq1imKdJmezuAJ67eALXGEmucd2zflEdKuZH98+ct+2yAuecP0U87gSepkDLUeGRIPPIix8F8OvwbyBxNPno1ECbAgmATF2EJiRN/ToZJdmCG/W3N2QRXt3PB3hvCZQsrPFYctTpvZUGg5kcPQ4RfjId30f0YXpvDBgXX9Nz3G1Qbr6hPmoEFis4Cl9sMRYGfLRNIIYaA0zpBtTKiQIUOZjadahW+99AVrJjflp/YErZ1Tmo1mEhEa+GSeqdf0XyKu+eNks+WCFqgD5kM1wAZPkOQXN+qGI8VQLxOYOxZQQANYRGIZ1dlAPJHr/S40rw2BYNvVg8vTRPHrqvm9paKlPeRYCDH5JoCc/5HikcWgaZI3IfodbS8Qq0CCbB34TuO2ZG5gFr2XFWsailj/weBhGKTV+D+CPoBDFvCpyUs44rBqEiZbIMZSPhQJiLONg5BGxHA076kfCbzv2ihoek8IZNzosZTijk1LI6bwMgBWfldo7NH0UIR9Pe1twSt1Hqk1V6IcDMhFNv7dnQkyhLRPHRPKx1/vAeiSZVKRPPp73CXFfvcGJcmujUyMc7KTA5HkQ9yzGtdGd2VV2Db8wjNRnQnLAlu/qOmQC5MloAPlXYyZ/attvRmXVHBVC/7ogLj1RTcYD0Gh7/1pL+3u4DhAw/J49qGwSVeb9Udm6gYzPnRh+o4zwn4BFDtCdnwliEHfGgusCHz/lSFzinOxDu/KJV3E8wWUsEX8eC6IzTOe3jTL09y+OCsSrlXvCQuMEJ/lYPDrGl0+mWi5xSo5lk0fk8onXHRyfwzmACv2oLRgrZnzV3q7pCDsIOqmfYekMx0tUzIZDsd5Cs9CGSCpYGNKNNl5xU2fn+Hnjk3Pueb0ODxpqQzbaxOvr0EGrj/ZwlTxldVNXq+NnrPLcKy5FVYBvcFdBer0XM71zI/nKJ+jmyMVMigddgiC5plKyJczKe0PrdHev1Pf6jn/A0R982fk4aAUs6WgWgcBmH7AMjwoMhm6nDkUkbfPS9vKdZ9xM4ga4OyE1dp575f/8Igf2zy9ySM+9Jl7bO1Pp0iup90wiiiOgvNfA4DpFe9uEVQdxvUSee/2zLhVYMkESBreg0BrFbGatVN85Hm0W5V4pb8w0/wwv5TPdr8XtsMWiFAVnQpD8jrpyLg2qm0dSPcYckyNbToo2VvQ/MD5Ar9kx7tY8JgRTNJvOGANyr9VDp8eM3OsrZpIij7HwxsKTAQG8xbqYOi4mlkrcZ5EXXk3FvRmrVWMjxuROEjjw3CUajidk4es0PIbfpaKrCHUDxokGDMxBjql3IiomCUTLGz+IpiBAPgBA7ekDebFExCmGcPoQrPA0Iext9pSxXpQ9ImFrbRkKzWKhUOc8QSsMJuOBVZwXrMghzUx54RVz4EAlVBGepsRp5rSzlHlxJmrpP+qI1Qycc8yno+M40btJIwYD1HR8AvIwoEUSvVscXuDlr1Ec5wYBh1LQViGA/O/9RQhXq6DF+ZF6OP7mlEqINaqhSNZAgxs6BvuBYaDDaEqN6HWGM4IvbJRLwiWm1qkJv9jUq9PXxYcLOYZuZCSm8K7ZNH/x9gACelX7SlfhuNmTYKhUFqKY1yF8K8LPgIsCZR0AR9+iAcHO+sC488AVAwR+U9/Xu3pjl7kaGbuO3VOVnFBJ6fWIz3JlfJiLoPQBLyvkVURcTNbnY/X3kiWdrHk5idEGvKyeJ+1mLfMU3CBQAsR3+ErlaITOqBI05qXvyZwFa0lbYbTguOfjhdz7kIP3yiA/q1GO/n2qm3p/2G1okpbpnBxw5U4u5qVXARjr9R1jHxN3jKU583KmcHgIR6ebngYMoFtxSDwpIUf+0usGJp3Vu41wXvOzL0m/DLDUYJff1AJm8l9W9X2zwXh8zmRAV+26zVJ71xedB6PXdKZa4SvvqxSu04WQF47pcDlzMWSIJd4aO3G5PuAyAGL20o3D65rxrKsws7BRs5FslE/kS00bSuTrXwr0EbvCRRA+QvRYPdfZXQ0u3S2Huw6k1M1nXrWp0e5qK1y2ruSyFXOmMj1YuX5kTzjzZz/d4z5+BVGwb40R8mhMhJ+5C1MOCgwo4ADUfDZRreAhlCLGKa7ct4CIuCdE08S1ZbAvJ/S+SBzMdHz3gizuGEM+82PIilyftbhJj1eO7AnNIAp8Z1YJdqOE2S6toJq8vlhmPeZATcsgkxgcFOivKZ8ViTauyF873EJy6r66fYx9YuumidaJG78GG+hG5le30ddwYjP9qCkvBtTReobqD5WrJdTAmA2DVKTtOAb0DF0UYBUMWaSTfki2Gk7bM1aLB/p3Uk+cwdqdqitOgAYVLOPKB/XIj/mYp1m6TSHZs7N3TnuR9qWJF0pDCIDTq/LDe/gJf+DD2a81XDHUO/cjOB31gyhImiO6eok5GfamQ8Lc+IIZJevYqYW7d7dG7tZyKs+W/UKrV9VAiUCFg2vuB3i+tTF7bDq8KUnnD/jo7iT+O9HDrAH53I/S4ApZq5N/pi9cXfKIqOJiBrnzuR95oSvZ3TmcqviG6jdv3eEbSh3BTF/uPQN5EfEXfkW8IJ63tdlo7nCbFmLMqGH5vFBV2zONnAofsonaYEI6/OWjImWgSCpY8c9A5nM/kp6UmCEy2hNZGQBMpGTA/eoT8jLkNgYK00HZ+1go/wGWcTrp1i3TbXwTCvCeohSwZ5i9wFwIWCea5WbXmWU9E6yce0tyU5EQ4Dikq6ehiE6i9kV05hyKxBg4WssrKusNpWglujgd8yY619AgiwpSvqy7b/t2yzet/vRue9f88fO7jMAWNqWIPSHuxMwDmPHsctc88/AOJrcVu33Zwoi8Nu/opT3Yk372XBIk+f+JncQ/42WEnTEW8V5bfHur7KebmsPwfsYRlqOn+l6AGeF3+8QrWOwpx+kPv4TfgV2/CX4F76/eimeidtE17lhPmPZpadSMLl48v77qwY1f5/EqrAwdjPeSxm5aHvBk3rq5gwtk6DXm4jXWq+hFuhdo+x0NTlebZt9goCDuDX7BC3ThqBw6ViwViV+AZCkIMVUQA8ktKiMJO+D2iMuu5ZwZVlbvNMc1lVwTJN72qWnpdyqJbciZc6QYlSfSSRDBp5PIOerLCbhbG157OP3rFhCOHU7POTIsVd+e0pC+trqBZKcFh4652k48jk38/cexUZKWhUOHsU1naHbxAZSCo9E4SbuZsqqnThzVcyHZNos70B1ZBmwXHIjGjMHJLY/gjrwXHG2WEAgyULi6gxQUxajwCBvSqXMvQSWCm3TnU111LvMX/uh3HXzoYDnbwK3YaIJQek14z7jiNh3i+67Bq41WfCDeS6NboODIM6pUJuXCkiM5uf4D1c9E9Wzo4g++puX/TaWkx+DxCPfMYQCCcr1b3tkvdOYF4QNZ7v4PhKzQcZGdNoVlqE/BAWPIl7r6BQjxvTFuHeEWaynZguPEEBwHf3jDFhWWm/1vGThonXLvD4PaJVDBkWSf8MKz6MAvFKcO/BYcPvYpdQj7U+oAdsHBX5RL1mfKe2y28BhUHJai3JTltsZq2yDrlv5AKnV6m1vfR3jbPPxrf0mbZXKB3sQirnFLnpQsOCDL1aFuIq+cI8bX4OPGNvv2wpMRjHrs53bV3L8If7hgI5ojRZSEFO1jO5fQsW3squuaB8xtm9yqVo8Vb1xnnJrh6xX1oDN+omeflhp+yL87zgnrEhTLneKCQ8EQQW5yQ0GQmqng2C7kBS9gR8daZFY8oOFuLbz+IDleweFav7aZPT6F3138QC7q3l+2EL2LNv+1+e9rdrtr8ISHIVxtTPH19VdbhGLUx63HKVv8H6sdCx9RaamGiDRBQgzq79cYsB0HAGJ5KgSw4HApFuwJuCLxvpCrgkOYCENnYMSyYwkYwbkfuz1UMsaCw5wQL04W5i7j0S217TsbkpVSLMDBSpEAG4ZY7u3CgqOKInbZXZEYdksOBIID3NWGho9VkIovkcevE/xyA16ZXSLuDB1pURUr8IeIvfmCw42ujabxXi4sjSGuaFOvMYAGjCt4lGZDDOB2YfLVhomIVKSQcH/xv1r0caGZFkABnciWiljTEOu2ZSuQ65Ywty2SPAUhSgfBJ/HMn/5MXsExRkDXiQhMSZiHoODQouu286HmnFcNynSmNRQ48wIusYnPjwjltlhlTSw4FAcFXdrVIGkrEHtTtl44oVemai04CAfQ01kegRK0lrvyrsY827FRwJSkXcARNuAyVhXKfARIDPJDFhxSEwnyIc4tHZlEsloLcDSNeW9PbW/2OZREhuRBTMQpLc4zJSCSGu5KQ7XnGBt2ifz168aeQfTZRN8E6UfJz8QSZtwHpzY+GkvCEi0B89ZYx99oxzCrnqtmbU/XHzb+J/R75u+yvx/usIlz2URxYre3JBNFBUfgMCl9EPd7feelMXhQfSIOvrk+7H0XOuxlr+EgGjqQgjsq9sJUQ8VSsMsvfFli6sFMC7h4gIwssHWAiR0oMA0w7blVC/3WkMwYukMD3N1kSgoEi+bDHZ9JKTgy56YSq+Zk/tGbw6Yn+WjBUTc39V/qowkI4uwDN3Xdk9ag4GAbjKoSZ6jhtz5SXXAQDXL2pIACWjr9E0oNpH4qOKiG0MPbcxA3vjun4MAZFLJ7WQ9+sx3KaS/thG33iv1t7jpW+nZzV4Po1omfqtdzMM1NfQeXhrreTL9V5+aImJt6WTfPybOmXW2+M++9/KN+MVbZYU1gKOJWI8iGd5vWL5YHaxhzDbT9Im6A4iJ9J1TBATKWf+gmH+YZusqnKPMYLn11jkDruTunKAsF5ueWSwrkYIIr52IUnSrRo3meRHgIywzmeYrZ5XYrza7Hkj7BUXEzNRoOM65sqqcauk4P1oqPbfk8RT99sT0aZf9mZfkQl0t/ZFv6M76VUr2VOPvRU/RcYTqlzzKy5kguJXkJyM4+GrZjJtsRuVGTzsye3me/9zxAVI7SY4CiA1o8q9IPDXqtXbbvVf1cr9vtEwdw7ysKd1OTtpW6rJ+vPIvDqpIg/pIttgOKmR0sIHcmB5iZJUCHwdR+Ve+SThMj8lk2xyUvuCtmYwncZ3pc1ugYsN4O5haJz3nzg0Mg2p30bRSziagjTAvNSU79Ggfj7D+7QgTIFUAVpkysepK2ft2Qv8I9OgySIutl2mszK1RtIvFLkODUb1gSr49+wLSRlUiNXcymChQ94km0dOZvkuvL/P21c2v5WfnKenrAJeRMQUbvXnxq4vGrVHgPgRtrZrUThio9J0FJMCXNziR3lMWQyhN5DIv5qEfQunRCUenqmY/TwtbyDGSlQTqfSFEx/8Pv4KddzaILjo3i4+dIjKS1OREExwr3dRnSZoptdIqsYp7L5skMzlQUXD9TzAvJbw0teTk9kcjWOnJFPbE6e0sChcbXfCrq7clWZzuMXg7OrQLQifKL9gH2Ep/djUcoiDRHiiixFLTv8yc33lEbZ0FN22YNW2V1tYfTS5jxF8/5yiqRR9U0IFXM56oKM89vzq/AaUO+wWW7qlPVIPXCEH9pdp2s7ShAMT9L1Wi34riYSmNcZOtS7+psJGGT1i5bBR7V2rc3jnAecVMcQAdXkNWuDDIL39UY/bk6rGnTdO8uBXuqNodqvX7xicxBYyp0TpOvmlo87mtxmGWfa03l9hN29rH0fsXZ5HUVRvAWJw9wXMoanQOP9zngtS7/dTCKyLsahv1IQ4ugAr6xOPtWv5xWBd9bbJYrFtKqOwWUyT1ILhvehUSMUmFYD6fcaWNazy1ZTOVD1Anx4mwmq1gldkASldhHtKrcHcxIujh0W4zh0TMg0BwpmArPztIAx9YzMfCxiwyIHeysztXyQyuYGOakxYt+C8EiBhYv09Eo/S70hKZwgpltOhpLCN/CaOkSQ4XroHj9Uw0B0hII3w02xOq9DbtU2WTFMV2jiXHWkukoHxDvXODGG3dgB+5R9xBJE3g6KoZAXXPCpkz7pNhEtBs7ukEXjni0WeWRCl7k+7KGZ+qlzfqAfAblvT9/52yM2+gY33Q0Pw4lGuWgUq06OwqVen8+ydGx9zceHa8gaGbQxPG4H0Hkx0w10h0TO9rKXoWws39fBUg7Ct+rMA7evoMIEeV7dWNwBfcxzJtyKakI3Ks+/cDJjCxR0qzpuFdx4ky4urfKJebxV9urVrYadhB8q19UwykK2dgDrsG9WhUgydMHCsydOEC4Xs2ycDIdAhWd9MSTXo1i4FRX5QqOg/cq20AKB91ZJ7269ED5ThKtC5Kj9LStV4sobJXbRbGlYaN6NSjYyf8okrxY2V4lcc48lrICvV0/OJbwJnEUwWL09mvGwD00cRLhxhfDsWT+GZx2nk56O7mApU8kfCwxvJ3oAvTePi/RY0CNkvd2cHZYiE5IvodEL8x7O7LNgxF3wyipR7of5r0d3N/6fGdDkbjJ9iuJvBH2OLptcG/v7nQqjWBbd5r3dm29iOudIusTHrlXBYI6xBhehzqY96qFH6IZwA/OAUSvVnyXkSvqBLQVDXt+JRPki9j0j3E+oDfgB0C/JuT7odXalyDzT407hjW60ndgbL9sljYvIbG8w2aEKgIxaqfPuufr9bGJtwjVB099ueyXAjKdoH7Zn7+tP0fmtAj1reIEchH+rn6I8rrduDLEChUsCNq3J2+Hmn+yJYQR/iov1bQIVVEbmsq1bQ04bb8lTU+EDpV1ADqKSvea1Y8fKircDgfnXvbf4Zx0OCJgsHJsgpoabltni0Je2rCaUJWjBGT2czQcxr4TBy3VB7Fx7rtrScdKQmWXQcfScHx1Pw5sTFtfOELY+p4gkrWRnpkufSjhI6bvQl4//pxfX9kKQt3ny/Z8srzXPATtV8m0GtNpqPr2JmUJHUwnGPkaJGxCrFChnyB99tYYHX2NTKdqtHChTsdw0hIL8+05mFA1YxifBiiYLx1GqIMdeG/BPbLe935X/z0hIe4NMlu8UOfsYZPuyBkWaJxlfZM+wbJzSRA8qDrCEl0naIZ6yIDfqVsJISBMpGrMHjHcajoN1fh4Tzx5XNUdM1TlH+vyGjNUV7OE2O/q6kmu2U8Yq7+yWM/ae+qV9uX4TVpLOCVqrwSsAo+oQXAFi3+trR/0gmUsD2Kfgjh18TzP7bea0oPwXgBNK3BQD1GBbr3rmDBHUfolpzaep4UQNZvOiJzoVOYsNX5dNqAHicdW4wEEX1tjHlbgscIfNipg7LDR8WJTDtZZQEqQvkyPQDya6hERwlyP1f2+tqfgjqZ7nHL0DyDhtbTGfGn9jqoPRRRGJ/CeSza3b3uOVdd4jQufbdB44eoIjixs1K6Q3Ux5a4eDDlvWYCPwHmZvcuDWIz1FOfQUwaBz5Gn8dtHpjxPU8B97LBqKFrxTJ3uVLQu7Fg00C4j0qOxkQZuQp80W3gLguB7Ic+pOwyilWngfcqhZHI8DspfZPzMXW2Yf5Mu9uPbHcF3+04aSMceXe7VrN+U4HATETXEKae0Bro8A1wJ44oD7rjJc1H23FiJAngAQl/pmeKtvABNe+muxCodF48LR50O2Y484PQ21Oo4qv0jpUF3Mvk2ZLgd+w2DpTA6obtPLT1gwfcjrSaccYwPccPSHph7nwjTFphQLlVtzNndSQUowkQ1sEWQDG8wERsdwRAownf1rOvM6g9HWZuxodtxECLP9YH+nsXEkQBm+0Lh5sje628xQ0/lIVyHiEBen5O8CwXTqm7Cisa5IJXLhqo4lcwHhOPtOWNFEV2R4dr6K26bvaO3CJk4FAZdFizG9Vrrd8uz84hMPW7bofLl+1YdWB66m8yJRif4erqajH6UvXVmyYq/RvecyE0nzF96QDI5omk4fbMhP516/6Vxs8PnxbOwJn189VdQJnObMvYb7wBTrgm43ScMY9N7y8mj1ZSOizRF3fiJu5MFIoFtM1nLMySTnZCgIJmSO7CFeEbLgLuz2IQxTjqkh3jisDstTUXVTjo0hQbnvjiXh1j5HwPBlP8nYMW6dCh2bcmBLKOeuEUWCjOGfctxKKBG/and7uZteOFwF85X4CWZR20tckWDLfTGKzoRo+s4zpCWvPCOp9I1nUw5SWVByFXFmBYKBIZhhHxxj/cAEoyj2OGvaac3RKxFyCCiAzL+SAz0WkKgl+ZLabfIdlRzesfjewIHU97tqA2db8SZ3KqOiq40sE3yvv9vdX2zPVyt/B9cAHLu7I1S8nhsTbsCLbPXd7++w0dzN4QYce7AwvGvH9D+wtXGQMnzMpu7tCViOQv25O3sqvLHn0fSi5t+VTUBCOc7x4A/XceJVPnjQG8NWQfyvlMaBQegdkXLfwkgMB6IzPDeVBQengAzUnkNVJQe43AaRdondcJFYBZvGOcUgrPwviQv4hM8lfRVfyVEyt9CTIbfYwLBhn0KNHCVHwXiAKniL1iGkxEWkQcnhL4Tw3XxbSJug/D9iEgIui+LnnZLjXvA7cCvsrTZ0yNvWrueLkoNcUMmzT2YhCHe/8mED+nRAYYIsp6GGVAxHjY429sxP8g3v/Kqv5EgXewBAHJGA2EZ1b92bnnMC4v46bjoHv3zd8AFtPmtmfw8dM6OYRNhcuN/7w9dszJUc8WKAWh6j4E//lxuQfJLpk9X0APJ2SFpB2nRI0sAoVHvOtd+riyntb7+XXnLoizusGgSGoRCTXEqbksNaOHGaunuQL/0TOb2JS7x6YlFewJKjWRKIKQQrNFNCvlOygO6lHH/C3O9fWn+fpTs+Q0RDsyR5sKbkkBNGcA6G9F1ZxKWdDanbskK0Vfq+rJLDUpgdNBcThRm6A7GeR1mmkhqnnZAlB6UIaDDw5KE5jw8UQUDxSVJ8Eb4LS9E5LkoOOwnEIynLXYTcMMNcV7vKrD5oO8TLwR3pjqIT8vUCvHrmRCBKx/BUrThhijjrTkBb2cJyMk08Rdj0uJU/NKm73GKPtbqj4z6aZOiEczlRumj9Iy7BGreRiqFlYUa2PsFyMksBJ868ifNFqrbo3Js+iFROlIrzBXQ8Il37hbF60dz6YEySajaEU07OElWCzbkKNZNolhRXFYmW+SiBjS6f5u5gZp8O8hJs60Qtkgl5+qpLopX5OFHx0DB37ErAo0jY8fJJXG3qW6WfBRHyGMEe9afjYJ3PNgWTlHj+RE0s4iTOuxT/6+sp8+IV7TypYclXMgRZ5moM6skBQNR0FgCWHMgDUOZlXx1RJqSopjAfEoOIGrIOQURvLHM1xESpB7iSOPlAmauhg15YaBdQqSu8culUKzsNYAIMscDEEUO17yyuJsDXyPLSKGQClEINDGj+smVJOHBUVfx2HD9scLIpYeXuGQ+1tlCDRXjHOUVRuKakQiz4CxSTFI4LX8lU/IpC6w1xKYs8hck7Qs7vrsDiUOOyUNpKORT8EjLqoniG3dEDa6eYxlgqH4NA/vJ9I19db15Ry4f4ZYSvEjQMwifziCr0WYiuH9s9pdImDD/2fPwL+ZQ6pC5KdGLxVYmMMR2lMTiTVyDt83uVU9VxrzbZ9RrUjC3o+LtebZCB6cF3nareO3TdIrHENy6y6NE7F8up6tTOhfaJUgQ7JEvw5ShcJIWjYd1Sjoz3csernE6T2DTUs989bh+SBRWRygAJ8lhVaXWT1Hi6QGfCRgLY4Ri9+QE039llZklI704Ppbo8n8Xm7EOuGir2pSiodMBf1RZa947iCSh+lhaXN8gFAMHlcmU5SkPwZXKBtL9iriyVZgxc6cYQ4a1uLHjavW5lOdG19V/tZqsbuN2tLJV2HM0ME/WYwZOUEfdKd6cfSgtjkU7KA6PWQ+oEZVkWr3ny0x5YPOjxZ8NGqDFg8EY17aUZvFStLNWAEF83RoTUjWNlqRTYvbLYvZFKgoMA8zRA1BkcKZgbyrMkQCzH/DOlt35ZPLQCc1xHF2GDePiyZ0r93TlMO/BnD+Ac3mBWm16Hl503Pjpe8VL0fhLkFmiWuxYdqXk5pdyV2dJQ0fAoZ2qAWHlHfnBbjfCe9F7sZCMWelCSd9GUMzWm/MhFOsmmJe7S6W/ej12jU87UoBAfXI4+YHgSWny2oxmh3FgIrWO/EzZiOtiI3rpPqbPpVE1qnOjsvRfGBK22jzBohcMPXdzAZDF1DUmWMzWkyHTDDKrzDJczNYLIOwGpSF8LWM7UePGjt78wdOJOmT8JXM7V+HTSzTKp8Rm0Ibhcxhrx/n6ZE66WKedqvPIL5l0rrAY37MFEo7NE9AmWcznwyI0RTsjO26WRDnFWd87coieDed6DufVLJL/TMi/S3Cu/c+eHFrGVN5/2yPHtR3i6kePZI2ee4KHb0nuHAJfjqEE3B7g/OOsN9JrH9oleY5luTDJtJrtoejZ557M01GAUfcr1cFkFG6jz+TDyyh8kCrL1hmP7RZiWs5yfpbGDEFxRRQrXop2NTkLbnrAnYhHHacTQlRUrk9ofO+tRFxnPFchbSa0Uxk5sdw+VjT4wqr80H619gnMWB9rJRM4viukj+oDwbm4Lq7XHp8RXzlJ31hZK3bNM06LckF675wLpgc6flWkwo43bdUXrgAjpkoi/Eg1hdOdfBhmfB056DGtA3GHPtDLY0cYF7NHeOuXmS+yrhLcqnDt2vXuCVWndSGT9CztftJVMSLPR6CiSTbhtTWKKdvRF0R7zbKRVg0e3Fd03KlzDXC7vFZmNtD7ILm0980J5w5UldkfGpVgmC6uVxes59oLm6L021pvFfCoLth4YZiOtQGqtOwwvULUyzEZas049zMWW1bELiYCp/zBX6jqiDhulNdRg4IZ5GE178jNDmBDnFI+6/Gyk9VgdpUhMXOFUNRvN++W9WaR03kpqZfPjO3oAOjOLs3NF7VpAuPliUT+Dg53cdF90XE0isRid+K1XcD4jWvFxBOHMhvRsH3awc/67miewLJgoZjZeJ5QIIk60rI41mdnQHLy8yuc73boU8EGKdqD6/PAsVkWC5LJ1/XVmY3C2dD+ZDYsIQhXstWZAi9TPBucQxFDy5vTVYzLd8swF7XgwOu+X3RzsUGZBiGDLUbqMpNOJn5O3kumGzCIodwbVS8tjqTMXu4MiR516iXc86OVK8McD65/y7Uksm972BF8f9o7A1+cb+zO+mjP5arx3KvFMCQh+vy64CEHiRfY2BgvX6grz6KpdvA/wFVSrVS0vwsM2sap3aipr+WwbHxPsP7WGeoycoF52hFqjk8WsS8ApfeiDpmniSAXvsJE0loDvXIYuwW/xEzlzz+kvybrabA/77Mthb/7Hcva2LCQ5CkIUKQi6VUtKunu2ZhxnpCXEG5JSOiXkjKOASPS4LxmRjniSgeckR3JCkZzsCXqDbz/hIZ9xABI+k3QyQUHghJ1xLBHypjxWQPhBf9V9TTcKkW+j/k7hPjMOJeInTZ5xoH4lzjy0mMK3Xq86dy7drh+uLjH9hP0J64i32fdmveZbLrLNwfzd2MBuvphUpLgzLX2mtoT3oBoteJuZp3yEuN1H8OqnF3szjmCKH8k5K6ymeN/FjKOPQiFxSAnfvXLSz/KJFHInOuC3P+orvBVmrdOKYIctJNCASRy/mhkH+GpZ6+B4l/3//KpxKMrz5Gvb09YYFPv7jmZ5kWQ+dPAOeNuZpb5C2WdXhNI0rJgVKvqR5Cfnsp58rEzt9EEJhDTDzf/8Xw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Activity = _t, #"Activity Key" = _t, Notes = _t, Index = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Activity", type text}, {"Activity Key", type text}, {"Notes", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Source", each if [Activity Key] = "ViewReport" then "Both" else "Power BI Activity Logs"),
				    #"Appended Query" = Table.Combine({#"Added Custom", #"Instrumentation Activities"})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

