table 'Feedback Type'
	lineageTag: ad21fa78-5551-4110-a800-41b38a4766d2

	column 'Survey type'
		dataType: string
		lineageTag: 8365340f-ef31-48bc-a136-a5259ed7b171
		summarizeBy: none
		sourceColumn: Survey type
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 116a4325-f45b-4760-ad13-ef455c9ea2b7
		summarizeBy: sum
		sourceColumn: Order

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Feedback Type' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8kksSS0uUQhKLS7IzytOVShILVIILU4tUtJRMlKK1YlWcszJgcsWA0UNlWJjAQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Survey type" = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Survey type", type text}, {"Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

