table 'PBI Datasources'
	lineageTag: 4797e35c-021a-42f6-a190-9067ebee6226

	measure 'Data Sources' = COUNTROWS('PBI Datasources')
		formatString: #,0
		lineageTag: 50406dde-68ce-4183-af32-69d60df91998

	measure 'Semantic Models per Data Source' = DIVIDE([PBI Scanned Semantic Models], [Data Sources])
		formatString: #,0.00
		lineageTag: 60ce9df4-8782-4098-829d-33ab655bb3d0

	column 'Data Source ID'
		dataType: string
		lineageTag: ad7cbdb4-043f-49c6-951a-f0c3b60e1ff5
		summarizeBy: none
		sourceColumn: Data Source ID

		annotation SummarizationSetBy = Automatic

	column Connector
		dataType: string
		lineageTag: 3e985653-e84a-41e0-b313-5479de65ee61
		summarizeBy: none
		sourceColumn: Connector

		annotation SummarizationSetBy = Automatic

	column 'Data Source Type'
		dataType: string
		lineageTag: 2f23f773-86de-40ba-ba4d-8bcc7e05b8bb
		summarizeBy: none
		sourceColumn: Data Source Type

		annotation SummarizationSetBy = Automatic

	column Url
		dataType: string
		lineageTag: 319a62bc-2293-42e4-be4a-f3414aa895b6
		summarizeBy: none
		sourceColumn: Url

		annotation SummarizationSetBy = Automatic

	column 'Extension Data Source Kind'
		dataType: string
		lineageTag: cff873c3-99cd-423a-9aa6-ddf73f538fac
		summarizeBy: none
		sourceColumn: Extension Data Source Kind

		annotation SummarizationSetBy = Automatic

	column 'Extension Data Source Path'
		dataType: string
		lineageTag: 85250d44-5e8a-4a24-908c-790a1551edc0
		summarizeBy: none
		sourceColumn: Extension Data Source Path

		annotation SummarizationSetBy = Automatic

	column Path
		dataType: string
		lineageTag: 3e31705e-7c08-43a7-84a0-31bae168dd3a
		summarizeBy: none
		sourceColumn: Path

		annotation SummarizationSetBy = Automatic

	column 'SharePoint Site Url'
		dataType: string
		lineageTag: b6c5d6e9-3f82-4698-951c-e08fb6e4d98c
		summarizeBy: none
		sourceColumn: SharePoint Site Url

		annotation SummarizationSetBy = Automatic

	column 'Server Name'
		dataType: string
		lineageTag: 88c8d93f-6002-4805-8326-25e2e3c264cc
		summarizeBy: none
		sourceColumn: Server Name

		annotation SummarizationSetBy = Automatic

	column 'Database Name'
		dataType: string
		lineageTag: d12a83bf-9465-46cc-912f-3e69018c2cc0
		summarizeBy: none
		sourceColumn: Database Name

		annotation SummarizationSetBy = Automatic

	partition 'PBI Datasources' = m
		mode: import
		queryGroup: 'Power BI Scan'
		source = ```
				let
				    Source = AzureStorage.DataLake(#"Data Lake URL"),
				    #"Filtered Rows1" = Table.SelectRows(Source, each Text.StartsWith([Folder Path], #"Data Lake URL" & "/"  & #"License Key" & "/pbi_scans/latest/")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows1", each [Attributes]?[Hidden]? <> true),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Hidden Files1",{"Content", "Name", "Date modified"}),
				    #"Filtered Hidden Files2" = Table.SelectRows(#"Removed Other Columns", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files2", "Transform File", each Json.Document([Content])),
				    #"Removed Columns" = Table.RemoveColumns(#"Invoke Custom Function1",{"Content"}),
				    #"Expanded Transform File" = Table.ExpandRecordColumn(#"Removed Columns", "Transform File", {"datasourceInstances"}, {"datasourceInstances"}),
				    #"Expanded datasourceInstances" = Table.ExpandListColumn(#"Expanded Transform File", "datasourceInstances"),
				    #"Expanded datasourceInstances1" = Table.ExpandRecordColumn(#"Expanded datasourceInstances", "datasourceInstances", {"datasourceType", "connectionDetails", "datasourceId", "gatewayId"}, {"datasourceType", "connectionDetails", "datasourceId", "gatewayId"}),
				    #"Sorted Rows" = Table.Sort(#"Expanded datasourceInstances1",{{"Date modified", Order.Descending}}),
				    #"Filtered Rows" = Table.SelectRows(#"Sorted Rows", each [datasourceId] <> null and [datasourceId] <> ""),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows", {"datasourceId"}),
				    #"Expanded connectionDetails" = Table.ExpandRecordColumn(#"Removed Duplicates", "connectionDetails", {"url", "extensionDataSourceKind", "extensionDataSourcePath", "path", "sharePointSiteUrl", "server", "database"}, {"connectionDetails.url", "connectionDetails.extensionDataSourceKind", "connectionDetails.extensionDataSourcePath", "connectionDetails.path", "connectionDetails.sharePointSiteUrl", "connectionDetails.server", "connectionDetails.database"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Expanded connectionDetails",{"Name", "Date modified", "gatewayId"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"datasourceId", "Data Source ID"}, {"connectionDetails.database", "Database Name"}, {"connectionDetails.server", "Server Name"}, {"connectionDetails.sharePointSiteUrl", "SharePoint Site Url"}, {"connectionDetails.path", "Path"}, {"connectionDetails.extensionDataSourcePath", "Extension Data Source Path"}, {"connectionDetails.extensionDataSourceKind", "Extension Data Source Kind"}, {"connectionDetails.url", "Url"}, {"datasourceType", "Data Source Type"}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Renamed Columns", "Connector", each if [Data Source Type] = "Extension" then [Extension Data Source Kind] else [Data Source Type]),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Conditional Column",{"Data Source ID", "Connector", "Data Source Type", "Url", "Extension Data Source Kind", "Extension Data Source Path", "Path", "SharePoint Site Url", "Server Name", "Database Name"}),
				    LastNonDemo = #"Reordered Columns",
				    
				    LastDemo = #"PBI Datasources Demo",
				    Final = if #"Is Demo" then LastDemo else LastNonDemo
				in
				    Final
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

