table 'PBI Dataflows'
	isHidden
	lineageTag: 1969ea5a-6866-4a98-8a83-d216367b1638

	column 'Workspace ID'
		dataType: string
		isHidden
		lineageTag: d29cb782-79e5-491a-94b9-a740f4c65e51
		summarizeBy: none
		sourceColumn: Workspace ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Workspace Name'
		dataType: string
		isHidden
		lineageTag: cf21de5f-1d35-4bb6-b642-2ae31ef738f9
		summarizeBy: none
		sourceColumn: Workspace Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Dataflow ID'
		dataType: string
		isHidden
		lineageTag: 2e872eb7-ed0a-4091-9e8f-98e06a4d0f63
		summarizeBy: none
		sourceColumn: Dataflow ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Dataflow Name'
		dataType: string
		isHidden
		lineageTag: f572d8cb-800a-45d1-8956-7b4ab91f47dd
		summarizeBy: none
		sourceColumn: Dataflow Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'PBI Dataflows' = m
		mode: import
		queryGroup: 'Power BI Scan'
		source =
				let
				    Source = #"PBI Dataflows - Base",
				    #"Removed Columns" = Table.RemoveColumns(Source,{"datasourceUsages", "Upstream Dataflow"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns", {"Dataflow ID"})
				in
				    #"Removed Duplicates"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

