table 'PBI Datasets Dataflows'
	isHidden
	lineageTag: 22c5a2d5-aab1-4ce1-9acd-3ef38666bd84

	column 'Dataset ID'
		dataType: string
		isHidden
		lineageTag: 1ca0c92e-d9ac-4f17-8187-4d917dd61a81
		summarizeBy: none
		sourceColumn: Dataset ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Dataflow ID'
		dataType: string
		isHidden
		lineageTag: ac101ea0-f79a-4132-a163-c5664e65b329
		summarizeBy: none
		sourceColumn: Dataflow ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'PBI Datasets Dataflows' = m
		mode: import
		queryGroup: 'Power BI Scan'
		source =
				let
				    Source = #"PBI Workspace Datasets - Base",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Dataset ID", "upstreamDataflows"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each [upstreamDataflows] <> null),
				    #"Expanded upstreamDataflows" = Table.ExpandListColumn(#"Filtered Rows", "upstreamDataflows"),
				    #"Expanded upstreamDataflows1" = Table.ExpandRecordColumn(#"Expanded upstreamDataflows", "upstreamDataflows", {"targetDataflowId"}, {"Dataflow ID"})
				in
				    #"Expanded upstreamDataflows1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

