table 'PBI Columns'
	lineageTag: b9f4219a-d2c9-4898-b4bc-6a2da23d3786

	measure 'Count of Columns' =
			
			IF (
			    ISCROSSFILTERED ( Reports ),
			    SUMX (
			        Reports,
			        CALCULATE (
			            COUNTROWS('PBI Columns'),
			            RELATEDTABLE('PBI Columns')
			        )
			    ),
			    COUNTROWS('PBI Columns')
			)
		formatString: #,0
		lineageTag: c28ca0a8-b259-46aa-a4e3-824a06a2b083

	measure 'Calculated Columns' =
			
			CALCULATE (
			    [Count of Columns],
			    KEEPFILTERS('PBI Columns'[Column Type] <> "Data")
			)
		formatString: #,0
		lineageTag: b2fbbf87-544a-431c-ad41-32563a23815b

	measure 'Column Expression Len Norm' =
			
			VAR _min = MINX(ALL(Reports), [Column Expression Length])
			VAR _max = MAXX(ALL(Reports), [Column Expression Length])
			VAR _current = [Column Expression Length]
			RETURN
			IF (
			    ISBLANK(_current) || _current = _min || _max = _min,
			    1,
			    DIVIDE ( _current - _min, _max - _min )
			)
		formatString: 0.00
		lineageTag: 656579f1-6ba5-4477-ba66-9267d1cef6af

	measure 'Column Expression Length' =
			
			SUMX (
			    VALUES ( 'Reports'),
			    CALCULATE (
			        SUM ( 'PBI Columns'[Calc Column Expression Length] ),
			        TREATAS (
			            VALUES ( 'PBI Reports'[Dataset ID] ),
			            'PBI Datasets'[Dataset ID]
			        )
			    )
			)
		formatString: 0
		lineageTag: 505a76c8-443a-4971-90dd-e7949a874f50

	column 'Dataset Table Key'
		dataType: string
		lineageTag: 302abb21-3cc9-45b3-90f0-adc42fbeb431
		summarizeBy: none
		sourceColumn: Dataset Table Key

		annotation SummarizationSetBy = Automatic

	column Column
		dataType: string
		lineageTag: a7fbf243-3644-46e6-a82c-2a2dcd8e60ea
		summarizeBy: none
		sourceColumn: Column

		annotation SummarizationSetBy = Automatic

	column 'Column Data Type'
		dataType: string
		lineageTag: b61346aa-5731-4f72-b95a-b2553f853b6b
		summarizeBy: none
		sourceColumn: Column Data Type

		annotation SummarizationSetBy = Automatic

	column 'Column Is Hidden'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 319adb71-0c02-4ecf-b7c7-7872c1e5033d
		summarizeBy: none
		sourceColumn: Column Is Hidden

		annotation SummarizationSetBy = Automatic

	column 'Column Type'
		dataType: string
		lineageTag: ee4a115a-ee2a-4147-ab44-7133679b6210
		summarizeBy: none
		sourceColumn: Column Type

		annotation SummarizationSetBy = Automatic

	column 'Column Expression'
		dataType: string
		lineageTag: 9c62ddf5-3b56-428e-91b9-2ea1b3f37449
		summarizeBy: none
		sourceColumn: Column Expression

		annotation SummarizationSetBy = Automatic

	column 'Calc Column Expression Length'
		dataType: int64
		formatString: 0
		lineageTag: cd790501-d747-4664-ac06-859874c3fee3
		summarizeBy: sum
		sourceColumn: Calc Column Expression Length

		annotation SummarizationSetBy = Automatic

	partition 'PBI Columns' = m
		mode: import
		queryGroup: 'Power BI Scan'
		source =
				let
				    Source = #"PBI Datasets Tables - Base",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"columns", "Dataset Table Key"}),
				    #"Expanded columns" = Table.ExpandListColumn(#"Removed Other Columns", "columns"),
				    #"Filtered rows 1" = Table.SelectRows(#"Expanded columns", each [columns] <> null),
				    #"Expanded columns1" = Table.ExpandRecordColumn(#"Filtered rows 1", "columns", {"name", "dataType", "isHidden", "columnType", "expression"}, {"Column", "Column Data Type", "Column Is Hidden", "Column Type", "Column Expression"}),
				    AddCalcColLength = Table.AddColumn(#"Expanded columns1", "Calc Column Expression Length", each Text.Length([Column Expression]), Int64.Type),
				    #"Changed Type" = Table.TransformColumnTypes(AddCalcColLength,{{"Column Is Hidden", type logical}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

