table 'PBI Dataflows Upstream'
	isHidden
	lineageTag: c32fa471-cac4-4c33-8c12-59f806031ca7

	column 'Dataflow ID'
		dataType: string
		isHidden
		lineageTag: 5b9aa529-c3e7-4bf3-940d-c1c3be35287f
		summarizeBy: none
		sourceColumn: Dataflow ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Target Dataflow ID'
		dataType: string
		isHidden
		lineageTag: 1b794158-c474-4d0d-b3ca-548bb3ba46f6
		summarizeBy: none
		sourceColumn: Target Dataflow ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CalculatedDataflowPath = PATH('PBI Dataflows Upstream'[Dataflow ID], 'PBI Dataflows Upstream'[Target Dataflow ID])
		isHidden
		lineageTag: 3faca2dd-516f-4d02-9533-ddbd1ea9ccb5
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'PBI Dataflows Upstream' = m
		mode: import
		queryGroup: 'Power BI Scan'
		source =
				let
				    Source = #"PBI Dataflows - Base",
				    #"Removed Columns" = Table.RemoveColumns(Source,{"datasourceUsages"}),
				    #"Expanded upstreamDataflows" = Table.ExpandListColumn(#"Removed Columns", "Upstream Dataflow"),
				    #"Expanded upstreamDataflows1" = Table.ExpandRecordColumn(#"Expanded upstreamDataflows", "Upstream Dataflow", {"targetDataflowId"}, {"Target Dataflow ID"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Expanded upstreamDataflows1",{"Workspace ID", "Workspace Name", "Dataflow Name"})
				in
				    #"Removed Columns1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

