table 'Performance Metrics'
	lineageTag: 60a59e26-983a-4189-b3e2-4d214eb0ec15

	measure 'Perf Impact Title' = "The Performance Impact on " & MAX('Page Session Metrics'[Page session metrics])
		lineageTag: 7e18c366-1d5a-4a15-8340-9e6668d6a992

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Metric Title' = ```
			
			VAR _stat = SELECTEDVALUE('Performance Stats'[Stat])
			VAR _metric = SELECTEDVALUE('Performance Metrics'[Metric])
			VAR _suffix = 
			SWITCH(
			    _stat,
			     "SUM", "Sum",
			     "P50", "Median",
			     "P75", "75th Percentile",
			     "P90", "90th Percentile",
			     "AVG", "Average",
			     BLANK()
			)
			RETURN
			SELECTEDVALUE('Performance Metrics'[Metric]) & IF(ISBLANK(_suffix),BLANK(), " - " & _suffix)
			```
		lineageTag: 2c217891-f26b-4655-a5b9-e3f1663aaf42

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unit Title' = "Unit: " & SELECTEDVALUE('Performance Metrics'[Unit])
		lineageTag: 06083393-75a7-4860-b559-85281320d676

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Metric
		dataType: string
		lineageTag: ed45ccb3-abc9-4dd6-9a04-fa78184b1756
		summarizeBy: none
		sourceColumn: Metric
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2ce5e439-87cc-485c-9716-e12da4bc8c50
		summarizeBy: sum
		sourceColumn: Order

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: 80c0ca8c-0edd-48f5-bde0-e82859bb6e75
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	partition 'Performance Metrics' = m
		mode: import
		queryGroup: Performance
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WciktSizJzM9T0lEyBOLg1GSlWJ1opZD8ksQcBeeAUIWQzNxUoIQRkmRgaWpRpUJAUX5yanFxZl46sjpjJHVhqUUlmQWJhQpe+UnIakyQ1LhWpCaXghyg4JKak1gJlDHFsCkotbg0p0QhKL+8GChnBsRgZmwsAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Metric = _t, Order = _t, Unit = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Metric", type text}, {"Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

