table 'Survey Questions'
	lineageTag: 3b0cad94-9beb-438f-93c2-49f27b297ef2

	measure 'Question Title' = SELECTEDVALUE('Survey Questions'[Question])
		lineageTag: fe392dc1-4211-4de4-bcde-ac111d3a6286

		annotation PBI_FormatHint = {"isText":true}

	column 'Question Key'
		dataType: string
		isHidden
		lineageTag: 86fdaf54-f919-43e9-9ce1-ad329022c123
		summarizeBy: none
		sourceColumn: Question Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Question
		dataType: string
		lineageTag: 6578a478-c20e-4852-9c2e-7899d60ebe2d
		summarizeBy: none
		sourceColumn: Question
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 55af1667-961e-41ff-9ffc-2518fd05cdf8
		summarizeBy: none
		sourceColumn: Order

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Survey Questions' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("ZYzLCoNADEV/ZcjaTV9/UBQ3Rao7mUUcQwmtUcy09PM7g1TB2QTuveekbaHiL1NO1HfonqXqmxQyuNM0zp56szYHsNmObnigGj8sjwjEZJYY0jHFcxYUx/gqhwmdD9DamAJZ4pNzql3JsfIom4XqaTb/PmqnVLtVdRiWewFrfw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Question Key" = _t, Question = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

