table 'Visual Scans'
	lineageTag: 03d3a062-ed8b-4f3d-9c99-a8819b286f4b

	measure 'Visual X' =
			
			VAR _scd = [Should use SCD for visuals]
			VAR _scd_res = CALCULATE([Visual X measure], KEEPFILTERS('Scan Attributes'[Calc] = "Visual Attribute"))
			VAR _res = MAX(Visuals[X])
			RETURN
			IF(_scd, _scd_res, _res)
		lineageTag: 6281601f-39bb-49d4-a55b-11f7b86304c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visual Y' =
			
			VAR _scd = [Should use SCD for visuals]
			VAR _scd_res = CALCULATE([Visual Y measure], KEEPFILTERS('Scan Attributes'[Calc] = "Visual Attribute"))
			VAR _res = MAX(Visuals[Y])
			RETURN
			IF(_scd, _scd_res, _res)
		lineageTag: 8674c394-09d8-4156-9765-fc15f36106e0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visual height' =
			
			VAR _scd = [Should use SCD for visuals]
			VAR _scd_res = CALCULATE([Visual height measure], KEEPFILTERS('Scan Attributes'[Calc] = "Visual Attribute"))
			VAR _res = MAX(Visuals[Height])
			RETURN
			IF(_scd, _scd_res, _res)
		lineageTag: fcbd2205-25a9-482b-af1d-38ed6bebfedb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visual width' =
			
			VAR _scd = [Should use SCD for visuals]
			VAR _scd_res = CALCULATE([Visual width measure], KEEPFILTERS('Scan Attributes'[Calc] = "Visual Attribute"))
			VAR _res = MAX(Visuals[Width])
			RETURN
			IF(_scd, _scd_res, _res)
		lineageTag: 63dfa467-22d0-4271-babd-3ae95bf17942

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visual Z' =
			
			VAR _scd = [Should use SCD for visuals]
			VAR _scd_res = CALCULATE([Visual Z measure], KEEPFILTERS ( 'Scan Attributes'[Calc] = "Visual Attribute" ) )
			VAR _res = MAX(Visuals[Z])
			RETURN
			IF(_scd, _scd_res, _res)
		lineageTag: 109e1444-154f-4cd8-a45e-f41fda0736c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Heatmap Visual Type' = ```
			
			VAR _visual_key = [Visual Key in Heatmap]
			VAR _visual_type_guid =
			CALCULATE (
			    MAX ( Visuals[Visual Type] ),
			    KEEPFILTERS ( Visuals[Visual Key] = _visual_key )
			)
			VAR _visual_type = 
			    CALCULATE ( MAX('All Visual Types'[Visual Type] ),
			    KEEPFILTERS ( 'All Visual Types'[GUID] = _visual_type_guid )
			)
			RETURN _visual_type
			
			```
		lineageTag: 3829e11a-7d26-4bde-9554-3b5a78429875

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'X Heatmap Cell Size' =
			
			[X Heatmap Cell Size2]
		isHidden
		lineageTag: 10c5d06a-e295-4bb0-9fc3-6dc3e0ba72e2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Scanned visuals' = DISTINCTCOUNT('Visual Scans'[Visual Key])
		lineageTag: 56d92dde-7358-4dfc-8f4a-ad8c2368cb3f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Heatmap Visual Border' = ```
			
			VAR _x_cell_size = [X Heatmap Cell Size2]
			VAR _y_cell_size = [Y Heatmap Cell Size2]
			VAR _x = MAX('X Dimension2'[X]) * _x_cell_size
			VAR _y = MAX('Y Dimension2'[Y]) * _y_cell_size
			VAR _pages = DISTINCTCOUNT('Visuals'[Report Page Key])
			VAR _visuals_in_cell = 
			CALCULATE ( 
			    COUNTROWS(Visuals),
			    KEEPFILTERS (
			        'Visuals'[X] <= _x + _x_cell_size && 'Visuals'[X] + 'Visuals'[Width] >= _x &&
			        'Visuals'[Y] <= _y + _y_cell_size && 'Visuals'[Y] + 'Visuals'[Height] >= _y
			    )
			)
			
			VAR _visuals_above_end_here = 
			CALCULATE (
			    COUNTROWS(Visuals),
			    KEEPFILTERS (
			        'Visuals'[Y] + 'Visuals'[Height] >= _y && 'Visuals'[Y] + 'Visuals'[Height] <= _y + _y_cell_size &&
			        'Visuals'[X] <= _x + _x_cell_size && 'Visuals'[X] + 'Visuals'[Width] >= _x
			    )
			)
			
			VAR _visuals_below_start_here = 
			CALCULATE (
			    COUNTROWS('Visuals'),
			    KEEPFILTERS (
			        'Visuals'[Y] >= _y && 'Visuals'[Y] <= _y + _y_cell_size &&
			        'Visuals'[X] <= _x + _x_cell_size && 'Visuals'[X] + 'Visuals'[Width] >= _x
			    )
			)
			
			VAR _left_visuals_end_here = 
			CALCULATE (
			    COUNTROWS('Visuals'),
			    KEEPFILTERS(
			        'Visuals'[X] + 'Visuals'[Width] >= _x && 'Visuals'[X] + 'Visuals'[Width] <= _x + _x_cell_size &&
			        'Visuals'[Y] <= _y + _y_cell_size &&  'Visuals'[Y] + 'Visuals'[Height] >= _y
			    )
			)
			
			VAR _right_visuals_start_here =
			CALCULATE (
			    COUNTROWS ('Visuals'),
			    KEEPFILTERS (
			        'Visuals'[X] >= _x && Visuals[X] <= _x + _x_cell_size &&
			        'Visuals'[Y] <= _y + _y_cell_size && 'Visuals'[Y] + 'Visuals'[Height] >= _y
			    )
			)
			
			VAR _visuals_with_top_left_corner = 
			    CALCULATE (
			        COUNTROWS ('Visuals'),
			        KEEPFILTERS (
			            'Visuals'[X] >= _x && 'Visuals'[X] <= _x + _x_cell_size &&
			            'Visuals'[Y] >= _y && 'Visuals'[Y] <= _y + _y_cell_size
			        )
			    )
			
			VAR _visuals_with_top_right_corner = 
			CALCULATE (
			    COUNTROWS ('Visuals'),
			    KEEPFILTERS (
			        'Visuals'[X] + 'Visuals'[Width] >= _x && 'Visuals'[X] + 'Visuals'[Width] <= _x + _x_cell_size &&
			        'Visuals'[Y] >= _y && 'Visuals'[Y] <= _y + _y_cell_size
			    )
			)
			
			VAR _visuals_with_bottom_left_corner = 
			CALCULATE (
			    COUNTROWS ('Visuals'),
			        KEEPFILTERS (
			        'Visuals'[X] >= _x && 'Visuals'[X] <= _x + _x_cell_size &&
			        'Visuals'[Y] + 'Visuals'[Height] >= _y && 'Visuals'[Y] + 'Visuals'[Height] <= _y + _y_cell_size
			    )
			)
			
			VAR _visuals_with_bottom_right_corner = 
			CALCULATE (
			    COUNTROWS ('Visuals'),
			        KEEPFILTERS (
			        'Visuals'[X] + 'Visuals'[Width] >= _x && 'Visuals'[X] + 'Visuals'[Width] <= _x + _x_cell_size &&
			        'Visuals'[Y] + 'Visuals'[Height] >= _y && 'Visuals'[Y] + 'Visuals'[Height] <= _y + _y_cell_size
			    )
			)
			
			RETURN
			SWITCH (
			    TRUE (),
			    _pages > 1 || ISBLANK(_visuals_in_cell), " ",
			    (_visuals_with_top_left_corner > 0 && _visuals_with_bottom_right_corner > 0) || (_visuals_with_top_right_corner > 0 && _visuals_with_bottom_left_corner > 0), "╋",
			    
			    _visuals_above_end_here > 0 && _visuals_with_bottom_left_corner = 0 &&  _visuals_with_bottom_right_corner = 0  && (_visuals_with_top_left_corner > 0 || _visuals_with_top_right_corner > 0), "┳",
			    _visuals_with_top_left_corner > 0 && _visuals_with_top_right_corner > 0 && _visuals_with_bottom_left_corner = 0 && _visuals_with_bottom_right_corner = 0, "┳",
			    
			    _visuals_below_start_here > 0 && _visuals_with_top_right_corner = 0 && _visuals_with_top_left_corner = 0 && (_visuals_with_bottom_left_corner > 0 || _visuals_with_bottom_right_corner > 0), "┷",
			    _visuals_with_top_left_corner = 0 && _visuals_with_top_right_corner = 0 && _visuals_with_bottom_left_corner > 0 && _visuals_with_bottom_right_corner > 0, "┷", 
			    
			    _right_visuals_start_here > 0 && _visuals_with_bottom_left_corner = 0 &&  _visuals_with_top_left_corner = 0 && (_visuals_with_bottom_right_corner > 0 || _visuals_with_top_right_corner > 0), "┫",
			    _visuals_with_top_left_corner = 0 && _visuals_with_top_right_corner > 0 && _visuals_with_bottom_left_corner = 0 && _visuals_with_bottom_right_corner > 0, "┫",
			    
			    _left_visuals_end_here > 0 && _visuals_with_top_right_corner = 0 && _visuals_with_bottom_right_corner = 0 && (_visuals_with_bottom_left_corner > 0 || _visuals_with_top_left_corner > 0), "┣",
			    _visuals_with_top_left_corner > 0 && _visuals_with_top_right_corner = 0 && _visuals_with_bottom_left_corner > 0 && _visuals_with_bottom_right_corner = 0, "┣", 
			
			    _visuals_with_top_left_corner = 0 && _visuals_with_top_right_corner = 0 && _visuals_with_bottom_left_corner = 0 && _visuals_with_bottom_right_corner > 0, "┛",
			    _visuals_with_top_left_corner = 0 && _visuals_with_top_right_corner = 0 && _visuals_with_bottom_left_corner > 0 && _visuals_with_bottom_right_corner = 0, "┗",
			    _visuals_with_top_left_corner > 0 && _visuals_with_top_right_corner = 0 && _visuals_with_bottom_left_corner = 0 && _visuals_with_bottom_right_corner = 0, "┎",
			    _visuals_with_top_left_corner = 0 && _visuals_with_top_right_corner > 0 && _visuals_with_bottom_left_corner = 0 && _visuals_with_bottom_right_corner = 0, "┓",
			    
			    _visuals_above_end_here > 0 || _visuals_below_start_here, "━",
			    _left_visuals_end_here > 0 || _right_visuals_start_here > 0, "┃",
			    _visuals_in_cell > 0, " ",
			    BLANK()
			)
			```
		isHidden
		lineageTag: db750bf5-6bda-4311-8f28-f0732d41d378
		dataCategory: Uncategorized

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visual Key in Heatmap' = ```
			
			VAR _x_cell_size = [X Heatmap Cell Size2]
			VAR _y_cell_size = [Y Heatmap Cell Size2]
			VAR _x = MAX('X Dimension2'[X]) * _x_cell_size
			VAR _y = MAX('Y Dimension2'[Y]) * _y_cell_size
			
			VAR _filtered_table = 
			FILTER (
			    Visuals,
			    Visuals[X] <= _x + _x_cell_size && Visuals[X] + Visuals[Width] >= _x &&
			        Visuals[Y] <= _y + _y_cell_size && Visuals[Y] + Visuals[Height] >= _y
			)
			
			VAR _filtered_with_clicks =
			SUMMARIZECOLUMNS(
			    'Visuals'[Visual Key],
			    _filtered_table,
			    "@clicks", [Click Events]
			)
			
			VAR _max_events =
			MAXX(
			    _filtered_with_clicks,
			    [@clicks]
			)
			
			RETURN
			MAXX (
			    FILTER(
			        _filtered_with_clicks,
			        [@clicks] = _max_events
			    ),
			    [Visual Key]
			)
			```
		lineageTag: 6002c14b-cc83-4ef5-b47d-9bed7f3781b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Y Heatmap Cell Size' =
			
			VAR _page_width = MAX('Pages'[Width])
			VAR _page_height = MAX('Pages'[Height])
			VAR _x_ratio = _page_width / 1280.0
			VAR _default_proportion = 1280.0 / 720.0
			VAR _proportion = DIVIDE ( _page_width, _page_height )
			VAR _corrected_height =
			IF ( _proportion < _default_proportion,
			    MAX(720, _page_height),
			    720 * MAX(1, _x_ratio)
			)
			RETURN
			_corrected_height / 36.0
		isHidden
		lineageTag: d88c1e5c-6607-4711-b043-f9c60966e833

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visual ID in Heatmap' =
			
			VAR _visual_key_in_heatmap = [Visual Key in Heatmap]
			VAR _result =
			CALCULATE(
			    MAX('Visuals'[Visual ID]),
			    KEEPFILTERS('Visuals'[Visual Key] = _visual_key_in_heatmap)
			)
			
			RETURN
			IF(ISBLANK(_result), "This location has no data.", _result)
		lineageTag: 9620ebf2-d6fc-4e0d-bb7f-30fd0bd94469

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visual Name in Heatmap' = ```
			
			VAR _visual_key_in_heatmap = [Visual Key in Heatmap]
			RETURN
			CALCULATE(
			    MAX('Visuals'[Visual Display Name]),
			    KEEPFILTERS('Visuals'[Visual Key] = _visual_key_in_heatmap)
			)
			
			```
		lineageTag: 484257da-0025-4986-b0e5-e19c02ad2c06

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Event Type in Heatmap' =
			
			VAR _visual_key = [Visual Key in Heatmap]
			VAR _event_type =
			CALCULATE (
			    MAX ('Clicks by Visual'[Event Type] ),
			    KEEPFILTERS ( Visuals[Visual Key] = _visual_key )
			)
			RETURN _event_type
		lineageTag: 2e15973a-e289-4ed2-92ff-3f2d15ef08e8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Heatmap Title' = ```
			
			VAR _top_pages = TOPN(1, 'Pages', [Clicks in Visual], DESC)
			VAR _page_name = 
			CALCULATE (
			    CONCATENATEX(
			        TOPN(1, 'Pages', [Clicks in Visual], DESC),
			        'Pages'[Page Name],
			        ", "
			    )
			)
			VAR _row_count = COUNTROWS(_top_pages)
			RETURN
			SWITCH ( TRUE(),
			    SUM(License[Capability Heatmaps]) < 1, "No data found",
			    ISBLANK([Scanned visuals]), "No data found",
			    _row_count > 3, "More than 3 pages are loaded in Heatmap.",
			    _row_count > 1, "Selected Pages: " & _page_name,
			    "Selected Page: " & _page_name )
			```
		lineageTag: c3005967-1f67-4167-a115-553442781504

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Clicks in Heatmap' =
			
			VAR _result =
			SUMX (
			    Visuals,
			    VAR _x_cell_size = [X Heatmap Cell Size2]
			    VAR _y_cell_size = [Y Heatmap Cell Size2]
			    VAR _x = MAX('X Dimension2'[X]) * _x_cell_size
			    VAR _y = MAX('Y Dimension2'[Y]) * _y_cell_size
			    RETURN
			    CALCULATE(
			        [Clicks in Visual],
			        KEEPFILTERS (
			            Visuals[X] < _x && Visuals[X] + Visuals[Width] > _x + _x_cell_size &&
			            Visuals[Y] < _y && Visuals[Y] + Visuals[Height] > _y + _y_cell_size
			        )
			    )
			)
			RETURN
			_result
		formatString: #,0
		lineageTag: ebd154d0-93db-4198-8114-ba9031afb647

	measure 'Last X SCD' =
			
			IF([Should use SCD for visuals],
			CALCULATE([Last X], 'Scan Attributes'[Calc] = "Visual Attribute"), MAX(Visuals[X]))
		lineageTag: 0037a084-7a8f-4587-a2d1-d7ba9a7012f9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Last X' =
			
			MAX('Visual Scans'[X])
		lineageTag: 5d7da1cf-16a8-456e-85c2-ce1cce939f11

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visual Y measure' = MAX('Visual Scans'[Y])
		isHidden
		lineageTag: d4a5f756-ac30-4e4c-b973-fc0cb0b19038

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visual X measure' = MAX('Visual Scans'[X])
		isHidden
		lineageTag: 9f14f0c5-92ea-4f30-98fb-bcd12423f445

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visual width measure' = MAX('Visual Scans'[Width])
		isHidden
		lineageTag: 31e84c1b-4193-4446-849b-f179286f8c06

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visual height measure' = MAX('Visual Scans'[Height])
		isHidden
		lineageTag: b2385ce9-5550-498b-8a17-3d7880a8bb50

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visual Z measure' = MAX('Visual Scans'[Z])
		isHidden
		lineageTag: 1de94bd5-b947-4e41-8331-32fb8c51a0e1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Is Heatmap Clicked' = IF(ISFILTERED('X Dimension2'[X]), 1, 0)
		lineageTag: eb206967-bda0-4867-a15d-dae9da9c498a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'X Heatmap Cell Size2' =
			
			VAR _page_width = MAX('Pages'[Width])
			VAR _page_height = MAX('Pages'[Height])
			VAR _y_ratio = _page_height / 720.0
			VAR _default_proportion = 1280.0 / 720.0
			VAR _proportion = DIVIDE ( _page_width, _page_height )
			VAR _corrected_height =
			IF ( _proportion < _default_proportion,
			    1280 * MAX(1, _y_ratio),
			    MAX(1280, _page_width)
			)
			RETURN
			_corrected_height / 56
		formatString: 0.00
		isHidden
		lineageTag: 8e266466-59e5-4493-89ed-5cace6fa4709

	measure 'Y Heatmap Cell Size2' =
			
			VAR _page_width = MAX('Pages'[Width])
			VAR _page_height = MAX('Pages'[Height])
			VAR _x_ratio = _page_width / 1280.0
			VAR _default_proportion = 1280.0 / 720.0
			VAR _proportion = DIVIDE ( _page_width, _page_height )
			VAR _corrected_height =
			IF ( _proportion < _default_proportion,
			    MAX(720, _page_height),
			    720 * MAX(1, _x_ratio)
			)
			RETURN
			_corrected_height / 55
		formatString: 0.00
		isHidden
		lineageTag: f1c147a6-d809-46df-8324-4a0e98842c33

	measure 'Clicks Crossfiltered by Heatmap' =
			
			VAR _isXFiltered = ISFILTERED('X Dimension2'[X])
			VAR _isXCrossFiltered = ISCROSSFILTERED('X Dimension2'[X])
			RETURN
			IF (
			    NOT(_isXCrossFiltered || _isXFiltered),
			    [Clicks in Visual],
			    [Clicks in Heatmap]
			)
		formatString: 0
		lineageTag: fd25bbc4-50b0-4673-9df6-e4e0065e085a

	measure 'Clicks Crossfiltered by Heatmap and Column' = ```
			
			VAR _isXFiltered = ISFILTERED('X Dimension2'[X])
			VAR _isXCrossFiltered = ISCROSSFILTERED('X Dimension2'[X])
			
			RETURN
			IF (
			    NOT(_isXCrossFiltered || _isXFiltered),
			    [Click Events],
			    VAR _x_current = MAX('X Dimension2'[X])
			    VAR _y_current = MAX('Y Dimension2'[Y])
			    VAR _filtered_visuals =
			    CALCULATETABLE (
			        VALUES('Clicks by Visual'[Visual Key]),
			        VAR _x_cell_size = [X Heatmap Cell Size2]
			        VAR _y_cell_size = [Y Heatmap Cell Size2]
			        VAR _x = _x_current * _x_cell_size
			        VAR _y = _y_current * _y_cell_size
			        RETURN
			        FILTER (
			            Visuals,
			            Visuals[X] < _x && Visuals[X] + Visuals[Width] > _x + _x_cell_size &&
			            Visuals[Y] < _y && Visuals[Y] + Visuals[Height] > _y + _y_cell_size
			        )
			    )
			    VAR _clicks = 
			    CALCULATE (
			        [Click Events],
			        _filtered_visuals
			    )
			    RETURN
			    _clicks
			)
			```
		formatString: #,0
		lineageTag: c67b7fc5-4bca-4ecb-bd04-a1c4a137536c

	column 'Visual ID'
		dataType: string
		isHidden
		lineageTag: 171b4c7a-83df-4c8c-aa30-a31cfe07e5bf
		summarizeBy: none
		sourceColumn: Visual ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Visual Display Name'
		dataType: string
		isHidden
		lineageTag: bb964899-b604-4d86-9cbf-8005e584dbec
		summarizeBy: none
		sourceColumn: Visual Display Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column X
		dataType: double
		isHidden
		lineageTag: 56fe5693-4c3b-4340-b809-56a51800f08f
		summarizeBy: none
		sourceColumn: X

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Y
		dataType: double
		isHidden
		lineageTag: 6ba29e1e-0e46-4c6d-96bb-084b719bf36a
		summarizeBy: sum
		sourceColumn: Y

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Z
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e682248e-bde3-4899-aef8-6fde10bbfdde
		summarizeBy: sum
		sourceColumn: Z

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Width
		dataType: double
		isHidden
		lineageTag: 9593fc13-3699-4c5e-8f23-b76d4e1e7061
		summarizeBy: sum
		sourceColumn: Width

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Height
		dataType: double
		isHidden
		lineageTag: 6767eba8-f50d-4e89-b7eb-acbc9137dd2d
		summarizeBy: sum
		sourceColumn: Height

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tab Order'
		dataType: int64
		formatString: 0
		lineageTag: 1512a9a6-09ce-4c9b-bf3f-d4015d9c452c
		summarizeBy: sum
		sourceColumn: Tab Order

		annotation SummarizationSetBy = Automatic

	column 'Report Page Key'
		dataType: string
		isHidden
		lineageTag: b43b97a7-e0b5-4c90-91e5-7d56c90c9938
		summarizeBy: none
		sourceColumn: Report Page Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Since
		dataType: dateTime
		formatString: General Date
		lineageTag: 33058ad4-54dd-43c1-b403-ed63f8e07701
		summarizeBy: none
		sourceColumn: Since

		annotation SummarizationSetBy = Automatic

	column Until
		dataType: dateTime
		formatString: General Date
		lineageTag: 4e59722a-8c39-449b-8115-8d1af5277e08
		summarizeBy: none
		sourceColumn: Until

		annotation SummarizationSetBy = Automatic

	column 'Date Since'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c802b174-297a-4d2c-b88d-f435ec0e6a3a
		summarizeBy: none
		sourceColumn: Date Since

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date Until'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ccbbc8fd-e181-4ced-92b9-b05e0c394cba
		summarizeBy: none
		sourceColumn: Date Until

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Visual Key'
		dataType: string
		isHidden
		lineageTag: e18ba145-15f0-4b5b-933e-d40e076a2e1b
		summarizeBy: none
		sourceColumn: Visual Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Performance Key'
		dataType: string
		isHidden
		lineageTag: f1159960-7938-4147-8992-4fc4893ea84d
		summarizeBy: none
		sourceColumn: Performance Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Visual Type'
		dataType: string
		lineageTag: 85c11770-d67f-4324-b539-5b65e441e2d3
		summarizeBy: none
		sourceColumn: Visual Type

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: c1257005-604b-4211-aec2-1ccd40ba84a6
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Report Name'
		dataType: string
		isHidden
		lineageTag: f5ca0eef-10fb-4008-902b-ef1cc241e2a0
		summarizeBy: none
		sourceColumn: Report Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Workspace ID'
		dataType: string
		lineageTag: 4023ddeb-97e0-4513-a73c-d495cc4e2dcd
		summarizeBy: none
		sourceColumn: Workspace ID

		annotation SummarizationSetBy = Automatic

	column 'Report ID'
		dataType: string
		lineageTag: 60d804de-ece1-4e25-8d48-29367aa8a62e
		summarizeBy: none
		sourceColumn: Report ID

		annotation SummarizationSetBy = Automatic

	column Workspace
		dataType: string
		isHidden
		lineageTag: d950740c-9b8a-4869-89e3-887ca29f709c
		summarizeBy: none
		sourceColumn: Workspace

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Visual Scans' = m
		mode: import
		source = ```
				let
				    Source = #"Inventory - Pages - Base 1",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Report Page Key", "Since", "Project", "Report ID", "Report Name", "Visuals", "Workspace ID", "Workspace", "Until", "Date Since", "Date Until"}),
				    beforeDemoPhase1 = #"Removed Other Columns",
				
				    #"Merged Demo Report IDs" = Table.NestedJoin(beforeDemoPhase1, {"Project", "Report Name"}, #"Inventory - Report IDs - Demo", {"Workspace Name", "Report Name"}, "Inventory - Report IDs - Demo", JoinKind.LeftOuter),
				    #"Expanded Inventory - Report IDs - Demo" = Table.ExpandTableColumn(#"Merged Demo Report IDs", "Inventory - Report IDs - Demo", {"Workspace ID", "Report ID"}, {"Inventory - Report IDs - Demo.Workspace ID", "Inventory - Report IDs - Demo.Report ID"}),
				    #"Added New Workspace ID" = Table.AddColumn(#"Expanded Inventory - Report IDs - Demo", "New Workspace ID", each if [Workspace ID] = null then [#"Inventory - Report IDs - Demo.Workspace ID"] else [Workspace ID]),
				    #"Added New Report ID" = Table.AddColumn(#"Added New Workspace ID", "New Report ID", each if [Report ID] = null then [#"Inventory - Report IDs - Demo.Report ID"] else [Report ID]),
				    #"Removed Old IDs" = Table.RemoveColumns(#"Added New Report ID" ,{"Inventory - Report IDs - Demo.Workspace ID", "Inventory - Report IDs - Demo.Report ID", "Workspace ID", "Report ID"}),
				    #"Renamed New ID Columns" = Table.RenameColumns(#"Removed Old IDs",{{"New Workspace ID", "Workspace ID"}, {"New Report ID", "Report ID"}}),
				    
				    afterDemoPhase1 = #"Renamed New ID Columns",
				    Phase1 = if #"Is Demo" then afterDemoPhase1 else beforeDemoPhase1,
				
				    #"Expanded Visuals" = Table.ExpandListColumn(Phase1, "Visuals"),
				    #"Expanded Visuals1" = Table.ExpandRecordColumn(#"Expanded Visuals", "Visuals", {"visual_id", "visual_type", "visual_display_name", "x", "y", "z", "width", "height", "tab_order"}, {"Visual ID", "Visual Type", "Visual Display Name", "X", "Y", "Z", "Width", "Height", "Tab Order"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Visuals1",{{"Visual ID", type text}, {"Visual Type", type text}, {"Visual Display Name", type text}, {"X", type number}, {"Y", type number}, {"Z", Int64.Type}, {"Width", type number}, {"Height", type number}, {"Tab Order", Int64.Type}, {"Since", type datetime}, {"Until", type datetime}, {"Date Since", type date}, {"Date Until", type date}, {"Report Page Key", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [Visual ID] <> null and [Visual ID] <> ""),
				    #"Reordered Columns" = Table.ReorderColumns(#"Filtered Rows",{"Report Page Key", "Visual ID", "Visual Type", "Visual Display Name", "X", "Y", "Z", "Width", "Height", "Tab Order", "Since", "Until", "Date Since", "Date Until"}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Reordered Columns", "Visual Key", each Text.Combine({[Report Page Key], [Visual ID]}, "---"), type text),
				    #"Added Custom" = Table.AddColumn(#"Inserted Merged Column", "Performance Key", each Text.Lower([Report ID] & "---" & [Visual ID])),
				    #"Merged Queries" = Table.NestedJoin(#"Added Custom", {"Visual Type"}, #"Visual Type Fix", {"Visual Type"}, "Visual Type Fix", JoinKind.LeftOuter),
				    #"Expanded Visual Type Fix" = Table.ExpandTableColumn(#"Merged Queries", "Visual Type Fix", {"GUID"}, {"GUID"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Expanded Visual Type Fix", "Custom", each if [GUID] = null then [Visual Type] else [GUID]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column",{"GUID", "Visual Type"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Custom", "Visual Type"}}),
				    
				    beforeDemoPhase2 = #"Renamed Columns",
				    
				    #"Replaced Value" = Table.ReplaceValue(beforeDemoPhase2,"image","dataLeakVisual",Replacer.ReplaceValue,{"Visual Type"}),
				    #"Added Index" = Table.AddIndexColumn(#"Replaced Value", "Index", 0, 1, Int64.Type),
				    #"Inserted Modulo" = Table.AddColumn(#"Added Index", "Modulo", each Number.Mod([Index], 9), type number),
				    #"Added Conditional Column1" = Table.AddColumn(#"Inserted Modulo", "Custom", each if [Modulo] = 0 and [Visual Type] = "scatterChart" then "charticulator58556A88422D44A99D9BF0052B958F87" else [Visual Type]),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Conditional Column1",{"Modulo", "Visual Type"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"Custom", "Visual Type"}}),
				    #"Inserted Modulo1" = Table.AddColumn(#"Renamed Columns1", "Modulo", each Number.Mod([Index], 25), type number),
				    #"Merged Queries1" = Table.NestedJoin(#"Inserted Modulo1", {"Modulo"}, UncertifiedDemo, {"Index"}, "UncertifiedDemo", JoinKind.LeftOuter),
				    #"Expanded UncertifiedDemo" = Table.ExpandTableColumn(#"Merged Queries1", "UncertifiedDemo", {"GUID"}, {"Visual Type.1"}),
				    #"Added Conditional Column2" = Table.AddColumn(#"Expanded UncertifiedDemo", "Custom", each if [Modulo] = 2 then [Visual Type.1] else [Visual Type]),
				    #"Removed Columns2" = Table.RemoveColumns(#"Added Conditional Column2",{"Index", "Visual Type", "Modulo", "Visual Type.1"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns2",{{"Custom", "Visual Type"}}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Renamed Columns2","ribbonChart","StackedBarChatWithTopN",Replacer.ReplaceText,{"Visual Type"}),
				    afterDemoPhase2 = #"Replaced Value2",
				    LastStep = if #"Is Demo" then afterDemoPhase2 else beforeDemoPhase2
				in
				    LastStep
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

