table 'Workspaces Scans'
	isHidden
	lineageTag: 814d76fa-766f-4376-99b7-a26799b64fee

	column 'Workspace ID'
		dataType: string
		isHidden
		lineageTag: 0228b24e-bfa9-45c8-8ef8-6feafe532139
		summarizeBy: none
		sourceColumn: Workspace ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Capacity ID'
		dataType: string
		isHidden
		lineageTag: 832b5d24-4738-4745-8ccb-d87de37c697c
		summarizeBy: none
		sourceColumn: Capacity ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Since
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: fa523f99-0631-47dd-95cc-264da2928c87
		summarizeBy: none
		sourceColumn: Since

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Until
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 7e0b3094-a995-4546-b278-186884a78183
		summarizeBy: none
		sourceColumn: Until

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Date Since'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 500b84a5-103a-493d-b397-018892891d75
		summarizeBy: none
		sourceColumn: Date Since

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date Until'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: cb0d57e6-c479-4d18-923d-060621f7638e
		summarizeBy: none
		sourceColumn: Date Until

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Workspaces Scans' = m
		mode: import
		source =
				let
				    source = #"Workspaces - Base",
				    #"Removed Other Columns" = Table.SelectColumns(source,{"Workspace ID", "Capacity ID", "Since"}),
				    #"Grouped Rows" = Table.Group(#"Removed Other Columns", {"Workspace ID"}, {{"data", each _, type table [Workspace ID=text, Capacity ID=text, Since=nullable datetime]}}),
				    #"Invoked Custom Function" = Table.AddColumn(#"Grouped Rows", "FnPrepareSCD", each FnPrepareSCD([data])),
				    #"Removed Columns" = Table.RemoveColumns(#"Invoked Custom Function",{"data"}),
				    #"Expanded FnPrepareSCD" = Table.ExpandTableColumn(#"Removed Columns", "FnPrepareSCD", {"Capacity ID", "Since", "Until", "Date Since", "Date Until"}, {"Capacity ID", "Since", "Until", "Date Since", "Date Until"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded FnPrepareSCD", each [Workspace ID] <> null and [Workspace ID] <> ""),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [Capacity ID] <> null and [Capacity ID] <> ""),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows1",{{"Since", type datetime}, {"Until", type datetime}, {"Date Since", type date}, {"Date Until", type date}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

