table 'All Visual Types'
	lineageTag: 29c81bbb-0d58-473e-afe3-61ec643b61b6

	column GUID
		dataType: string
		isHidden
		lineageTag: e125e049-6f93-4125-b693-bbee15ab2135
		summarizeBy: none
		sourceColumn: GUID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Visual Type'
		dataType: string
		lineageTag: 58e4ec43-4dff-4f56-9d6e-0e8413f60757
		summarizeBy: none
		sourceColumn: Visual Type

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: 6147609a-aed5-48e4-9e58-6dc2513b9bb3
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column Publisher
		dataType: string
		lineageTag: de4628c7-5c1d-4b59-9931-22acedf7adea
		summarizeBy: none
		sourceColumn: Publisher

		annotation SummarizationSetBy = Automatic

	column 'Visual State'
		dataType: string
		isHidden
		lineageTag: 2068b805-1f52-47d0-b67a-d3d3aad3420c
		summarizeBy: none
		sourceColumn: Visual State

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 6364b1f0-7f23-4f1d-96d7-2d5a8b062be1
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Image
		dataType: string
		lineageTag: 46634519-e569-4ba3-b34e-7ed1d14bd675
		summarizeBy: none
		sourceColumn: Image

		annotation SummarizationSetBy = Automatic

	column Popularity
		dataType: double
		lineageTag: bc108bcc-95c9-434b-b238-0ea15803de86
		summarizeBy: sum
		sourceColumn: Popularity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '# of Ratings'
		dataType: int64
		formatString: 0
		lineageTag: 83c130d1-d90f-45b3-ad5c-e39c8abf4749
		summarizeBy: sum
		sourceColumn: # of Ratings

		annotation SummarizationSetBy = Automatic

	column 'Average Rating'
		dataType: int64
		formatString: 0
		lineageTag: c6eac968-c744-4125-9221-94d6ad4c74cf
		summarizeBy: sum
		sourceColumn: Average Rating

		annotation SummarizationSetBy = Automatic

	partition 'All Visual Types' = m
		mode: import
		source =
				let
				    Source = Table.Combine({#"Built In Visuals", #"Custom Visuals", #"Unlisted Visuals", #"Unknown Visuals"}),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Is Certified", "Visual State"}}),
				    #"Remove Duplicate GUID" = Table.Distinct(#"Renamed Columns", {"GUID"})
				in
				    #"Remove Duplicate GUID"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

