table Answers
	lineageTag: 00cd090c-4225-4e98-8a2c-d6cb174209e9

	measure 'Answer Score' = SUM(Answers[Feedback])
		formatString: 0
		lineageTag: 09ffe024-732c-4d1b-b989-ddea3066afe9

	column Answer
		lineageTag: 1fc14cf7-98a0-4373-a0d5-286488e951eb
		summarizeBy: none
		isNameInferred
		sourceColumn: Survey[Answer]
		sortByColumn: Feedback

		annotation SummarizationSetBy = Automatic

	column Feedback
		formatString: 0
		lineageTag: 1c9a175a-3783-4b62-9806-3b76025d543b
		summarizeBy: none
		isNameInferred
		sourceColumn: Survey[Feedback]

		annotation SummarizationSetBy = Automatic

	column 'Question Key'
		isHidden
		lineageTag: 184fb29e-a341-414d-889c-3c1575578bd6
		summarizeBy: none
		isNameInferred
		sourceColumn: Survey[Question Key]

		annotation SummarizationSetBy = Automatic

	partition Answers = calculated
		mode: import
		source = ```
				SUMMARIZE(Survey, Survey[Answer], Survey[Feedback], Survey[Question Key]) 
				```

	annotation PBI_Id = 8e1f84293de04c519b431501038b9d61

