table 'Data Selections'
	lineageTag: 16b2b4c8-bb65-4524-8f5a-7d3403ee0946

	measure 'Views or Clicks' = COUNTROWS('Data Selections')
		formatString: #,0
		lineageTag: 7c908115-dc58-42e8-a422-c64372f7bdb3

		changedProperty = IsHidden

	measure 'Page Link from Data Selection' =
			
			VAR _page_key = SELECTEDVALUE('Data Selections'[Report Page Key])
			RETURN
			CALCULATE(MAX('Pages'[Page URL]), KEEPFILTERS('Pages'[Report Page Key] = _page_key))
		lineageTag: b46bdbdf-6751-4e75-994d-c491b23dedb0
		dataCategory: WebUrl

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isText":true}

	measure 'Last Selected At' = LASTDATE('Data Selections'[Date])
		formatString: dd-MMM-yy
		lineageTag: 2be802c6-acd8-42e0-850b-04366e9b0fe9

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Filtered Column'
		dataType: string
		lineageTag: ce48ba39-a5f9-47f2-896a-dcefea8d8a63
		summarizeBy: none
		sourceColumn: Filtered Column

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Filtered Values'
		dataType: string
		lineageTag: edb1f42d-2f79-40e9-8174-9d974b0d1456
		summarizeBy: none
		sourceColumn: Filtered Values

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Filtered Distinct Count'
		dataType: double
		formatString: 0
		lineageTag: aaa2b29e-578b-4f6d-919d-8a70e50c6040
		summarizeBy: sum
		sourceColumn: Filtered Distinct Count

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Filtered Table'
		dataType: string
		lineageTag: 42ec5846-679d-4b3d-bfc3-0ea8f2974def
		summarizeBy: none
		sourceColumn: Filtered Table

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'User Key'
		dataType: string
		lineageTag: bee444cf-14d4-41f6-9f49-bd57b16eddd1
		summarizeBy: none
		sourceColumn: User Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: dd10aa26-d358-442a-a94a-1cc8bbc434a9
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 6ea5fd4f-a76d-4b9b-9972-7919144df0e0
		summarizeBy: none
		sourceColumn: Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Event Type'
		dataType: string
		isHidden
		lineageTag: 819de302-13db-4499-943c-1f77cbb8114d
		summarizeBy: none
		sourceColumn: Event Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Report Page Key'
		dataType: string
		isHidden
		lineageTag: 6230ad81-1037-45b5-acbc-22123a322818
		summarizeBy: none
		sourceColumn: Report Page Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Created On'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2db9113e-3eef-4fc6-9133-6dc3af772305
		summarizeBy: none
		sourceColumn: Created On

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Report Key'
		dataType: string
		lineageTag: a870be8e-e476-477f-92ca-8cc2bb1839b8
		summarizeBy: none
		sourceColumn: Report Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Data Selections' = m
		mode: import
		source =
				let
				    Source = #"Data Selections - Base",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Event Type] <> "RLS")),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"RLS Expected Rows", "RLS Actual Rows", "RLS Role"})
				in
				    #"Removed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

