table 'Feedback Icons'
	lineageTag: 1c890b16-990a-46a9-84bd-030584413c1a

	column 'Feedback Score'
		dataType: int64
		formatString: 0
		lineageTag: eb977045-4491-41a8-863c-32d629d347db
		summarizeBy: none
		sourceColumn: Feedback Score

		annotation SummarizationSetBy = Automatic

	column Icon
		dataType: string
		lineageTag: de836fa7-7333-45e7-87a2-c9717f064b86
		summarizeBy: none
		sourceColumn: Icon
		sortByColumn: 'Feedback Score'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Feedback Icons' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUfowf0azUqxOtJIBhDMBzNEFST2asfP9jn6l2FgA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Feedback Score" = _t, Icon = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Feedback Score", Int64.Type}, {"Icon", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

