table 'license-status json'
	lineageTag: 5e829e3a-d1c8-4c9d-beb9-7d4982e2576e

	column license_key
		dataType: string
		lineageTag: 01c15966-fcca-43ae-9b1c-4f7d23d3c901
		summarizeBy: none
		sourceColumn: license_key

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 3f924ecd-fef0-4383-809d-2f9264e4f8c8
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column tier
		dataType: string
		lineageTag: 270736cd-d954-47dd-943e-9295ff2c241e
		summarizeBy: none
		sourceColumn: tier

		annotation SummarizationSetBy = Automatic

	column message
		dataType: string
		lineageTag: 1aec92a2-21c9-44b7-9e75-5c02d4739dff
		summarizeBy: none
		sourceColumn: message

		annotation SummarizationSetBy = Automatic

	column exceeded
		dataType: string
		lineageTag: 07687a38-ddb1-47c0-91f7-0cf27fcff179
		summarizeBy: none
		sourceColumn: exceeded

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: b6ab93c8-7268-46c7-9cfa-c5ddd8a78193
		summarizeBy: none
		sourceColumn: updated_at

		annotation SummarizationSetBy = Automatic

	partition 'license-status json' = m
		mode: import
		source =
				let
				
				    ADLSPathDelimiter = if #"Is SaaS" then "-" else "/",
				    Source = AzureStorage.DataLake(#"Data Lake URL" & ADLSPathDelimiter & #"License Key", [HierarchicalNavigation=true]),
				    LicenseResponse = Json.Document(Source{[Name="license-status.json"]}[Content]),
				    status = LicenseResponse[status],
				    LicenseTable = LicenseResponse,
				    #"Converted to Table" = Record.ToTable(LicenseTable),
				    #"Transposed Table" = Table.Transpose(#"Converted to Table"),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Transposed Table", [PromoteAllScalars=true]),
				    #"Expanded exceeded" = Table.ExpandListColumn(#"Promoted Headers", "exceeded"),
				    res =
				        if status = "active" then
				            #"Expanded exceeded"
				        else
				            error Error.Record("License error" , LicenseResponse[message], "Failed to refresh BI Pixie. "  & LicenseResponse[message]),
				    #"Changed Type" = Table.TransformColumnTypes(res,{{"updated_at", type datetime}, {"message", type text}, {"exceeded", type text}, {"tier", type text}, {"status", type text}, {"license_key", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

