table 'PBI Datasets'
	lineageTag: c2906e76-3415-4ade-8ea8-743bea8719c9

	measure 'PBI Scanned Semantic Models' =
			
			IF (
			    ISCROSSFILTERED( Reports ),
			    DISTINCTCOUNT('PBI Reports'[Dataset ID]),
			    COUNTROWS('PBI Datasets')
			)
		lineageTag: 7565aa9c-04c2-40a3-b41b-4838ed3e32f8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Date Modified'
		dataType: dateTime
		formatString: General Date
		lineageTag: 84d5640e-1793-4db5-9c03-d50e86d2fe96
		summarizeBy: none
		sourceColumn: Date Modified

		annotation SummarizationSetBy = Automatic

	column 'Workspace ID'
		dataType: string
		isHidden
		lineageTag: 6f96f6ff-85c4-4bae-898d-58f5ff1927ad
		summarizeBy: none
		sourceColumn: Workspace ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Dataset ID'
		dataType: string
		lineageTag: bbec1aba-9939-4cd4-86dd-2454e0e32c65
		summarizeBy: none
		sourceColumn: Dataset ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Dataset Name'
		dataType: string
		lineageTag: 634286ff-c505-4c64-bb2c-6c9aaff8ebc4
		summarizeBy: none
		sourceColumn: Dataset Name

		annotation SummarizationSetBy = Automatic

	column 'Configured By'
		dataType: string
		lineageTag: b059e078-6d24-48b5-9f50-39c9bc7fc3c0
		summarizeBy: none
		sourceColumn: Configured By

		annotation SummarizationSetBy = Automatic

	column 'Created DateTIme'
		dataType: dateTime
		formatString: General Date
		lineageTag: 1abb2542-cccb-4ec1-b862-a98e4552803f
		summarizeBy: none
		sourceColumn: Created DateTIme

		annotation SummarizationSetBy = Automatic

	column 'Content Provider Type'
		dataType: string
		lineageTag: f2d2c09f-cf30-4928-a311-c1dea632ee06
		summarizeBy: none
		sourceColumn: Content Provider Type

		annotation SummarizationSetBy = Automatic

	column 'Workspace Name'
		dataType: string
		isHidden
		lineageTag: d2a5848d-aa8a-493b-93a1-754ebe738995
		summarizeBy: none
		sourceColumn: Workspace Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Endorsement
		dataType: string
		isHidden
		lineageTag: de7e8b10-f4db-4128-8279-5b86be84f169
		summarizeBy: none
		sourceColumn: Endorsement

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'PBI Datasets' = m
		mode: import
		queryGroup: 'Power BI Scan'
		source = ```
				let
				    Source = #"PBI Workspace Datasets - Base",
				    #"Removed Columns" = Table.RemoveColumns(Source,{"datasourceUsages"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"createdDate", type datetime}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"configuredBy", "Configured By"}, {"Date modified", "Date Modified"}, {"createdDate", "Created DateTIme"}, {"contentProviderType", "Content Provider Type"}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"configuredById", "tables", "isEffectiveIdentityRequired", "isEffectiveIdentityRolesRequired", "targetStorageMode"}),
				    #"Expanded endorsementDetails" = Table.ExpandRecordColumn(#"Removed Columns1", "endorsementDetails", {"endorsement"}, {"endorsement"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded endorsementDetails",{{"endorsement", "Endorsement"}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns1",{"upstreamDataflows"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns2",null,"None",Replacer.ReplaceValue,{"Endorsement"}),
				    
				    LastNonDemo = #"Replaced Value",
				
				    #"Added Index" = Table.AddIndexColumn(LastNonDemo, "Index", 0, 1, Int64.Type),
				    #"Inserted Modulo" = Table.AddColumn(#"Added Index", "Modulo", each Number.Mod([Index], 6), type number),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Modulo",{{"Modulo", type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type1", {"Modulo"}, #"Dataset Endorsement Types", {"Order"}, "Dataset Endorsement Types", JoinKind.LeftOuter),
				    #"Expanded Dataset Endorsement Types" = Table.ExpandTableColumn(#"Merged Queries", "Dataset Endorsement Types", {"Endorsement"}, {"Endorsement.1"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Expanded Dataset Endorsement Types",null,"None",Replacer.ReplaceValue,{"Endorsement.1"}),
				    #"Removed Columns3" = Table.RemoveColumns(#"Replaced Value1",{"Endorsement"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns3",{{"Endorsement.1", "Endorsement"}}),
				    LastDemo = #"Renamed Columns2",
				    #"Removed Columns4" = Table.RemoveColumns(LastDemo,{"Index", "Modulo"}),
				    Final = if #"Is Demo" then #"Removed Columns4" else LastNonDemo
				in
				    Final
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

