table 'PBI Tables'
	lineageTag: dd1a1257-a120-4723-8019-ceaabbe50f1b

	column 'Dataset ID'
		dataType: string
		isHidden
		lineageTag: ebe85ec5-45fc-4ec6-9aab-190d98f66ec9
		summarizeBy: none
		sourceColumn: Dataset ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Table
		dataType: string
		lineageTag: 3e21fafa-f6e5-4957-ae14-c4fa3e100026
		summarizeBy: none
		sourceColumn: Table

		annotation SummarizationSetBy = Automatic

	column Expression
		dataType: string
		lineageTag: b1dcd953-d5f5-4f14-831e-a2dd93608fff
		summarizeBy: none
		sourceColumn: Expression

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: b48149a5-45dd-4a05-b7eb-ddccd21a2ac8
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column 'Dataset Table Key'
		dataType: string
		isHidden
		lineageTag: 37d773ec-ddca-4923-bc50-b523dd41243c
		summarizeBy: none
		sourceColumn: Dataset Table Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'PBI Tables' = m
		mode: import
		queryGroup: 'Power BI Scan'
		source =
				let
				    Source = #"PBI Datasets Tables - Base",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Dataset ID", "Table", "source", "description", "Dataset Table Key"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"description", "Description"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each true),
				    #"Expanded source" = Table.ExpandListColumn(#"Filtered Rows", "source"),
				    #"Expanded source1" = Table.ExpandRecordColumn(#"Expanded source", "source", {"expression"}, {"Expression"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded source1",{{"Expression", type text}}),
				    LastNonDemo = #"Changed Type",
				    LastDemo = Table.TransformColumns(LastNonDemo, {{"Expression", each Text.Start(_, 200) & "...", type text}}),
				    Final = if #"Is Demo" then LastDemo else LastNonDemo
				in
				    Final

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

