table 'PBI Dataflows Datasources'
	isHidden
	lineageTag: 985f7ea3-4d36-4396-8be7-7efe0dd49559

	column 'Dataflow ID'
		dataType: string
		isHidden
		lineageTag: 8bc7d6b1-165f-466f-8b7b-4e46a53fd127
		summarizeBy: none
		sourceColumn: Dataflow ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data Source ID'
		dataType: string
		isHidden
		lineageTag: 81831786-0809-4110-b96b-8fd22a0a58ad
		summarizeBy: none
		sourceColumn: Data Source ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'PBI Dataflows Datasources' = m
		mode: import
		queryGroup: 'Power BI Scan'
		source =
				let
				    Source = #"PBI Dataflows - Base",
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Upstream Dataflow"}),
				    #"Expanded datasourceUsages" = Table.ExpandListColumn(#"Removed Columns", "datasourceUsages"),
				    #"Expanded datasourceUsages1" = Table.ExpandRecordColumn(#"Expanded datasourceUsages", "datasourceUsages", {"datasourceInstanceId"}, {"Data Source ID"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded datasourceUsages1", each [Data Source ID] <> null and [Data Source ID] <> ""),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Workspace ID", type text}, {"Workspace Name", type text}, {"Dataflow ID", type text}, {"Dataflow Name", type text}, {"Data Source ID", type text}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type",{"Workspace ID", "Workspace Name", "Dataflow Name"})
				in
				    #"Removed Columns1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

