table 'Performance Users'
	lineageTag: f22561c9-fdd6-4de7-a3b7-2cbabbb56ede

	measure 'Performance Value by User' =
			
			IF(
			    SELECTEDVALUE('Performance Stats'[Stat]) = "SUM",
			    SUM('Performance Users'[Value]),
			    DIVIDE(SUM('Performance Users'[Weighted Value]), [Performance Log Count (Users)])
			)
		formatString: #,0.00
		lineageTag: f99815b6-7429-4df3-b995-59e22ffc9301

	measure 'Performance Log Count (Users)' = SUM('Performance Users'[Log Count])
		formatString: #,0
		lineageTag: 8d305a4b-f2ba-4dc4-bf1b-dc09a0ef308a

	measure 'Total CPU Time per Click' =
			
			VAR _clicks = [Clicks in Visual]
			VAR _total_cpu = [Total CPU Time]
			RETURN
			DIVIDE(_total_cpu, _clicks)
		formatString: #,0.00
		lineageTag: 70c06451-7971-4f70-ab11-f157574e995a

	measure 'Total CPU Time' = ```
			
			
			VAR _all_metrics = FILTER(ALL('Performance Metrics'[Metric]), 'Performance Metrics'[Metric] = "Total CPU Time")
			VAR _all_stats = FILTER(ALL('Performance Stats'[Stat]), 'Performance Stats'[Stat] = "SUM")
			
			VAR _total_cpu = 
			CALCULATE(
			    [Performance Value by User],
			    _all_metrics,
			    _all_stats
			)
			RETURN
			_total_cpu
			```
		lineageTag: 0a943580-1dd2-4d05-958f-3a71be1aa87a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Performance Tracked Users' = DISTINCTCOUNT('Performance Users'[User])
		lineageTag: f1a640b3-248c-454a-9ee5-e9146103fda8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Clicks per Second of Total CPU' =
			
			VAR _clicks = [Clicks in Visual]
			VAR _total_cpu = [Total CPU Time]
			RETURN
			DIVIDE(_clicks, _total_cpu)
		lineageTag: 583456c3-881f-41c4-b5a1-9eef5ecd0430

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column User
		dataType: string
		isHidden
		lineageTag: 348b6267-a40f-40f6-a203-7c7df9c36e9a
		summarizeBy: none
		sourceColumn: User

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Performance Key'
		dataType: string
		isHidden
		lineageTag: 16a42669-bf79-4808-b139-ff7bfb2ac3bb
		summarizeBy: none
		sourceColumn: Performance Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Consumption Method'
		dataType: string
		lineageTag: 115a53b3-c0ba-4834-9a17-65f9af9b3d56
		summarizeBy: none
		sourceColumn: Consumption Method

		annotation SummarizationSetBy = Automatic

	column 'Log Count'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5c63be57-d924-4a67-a8aa-a817b0d19396
		summarizeBy: sum
		sourceColumn: Log Count

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: bcbc6c5c-3e6f-4b3c-ba28-148381f8b2a1
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Metric
		dataType: string
		lineageTag: 77570c2d-11e9-42fd-99b6-779c20e0a6d6
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

	column Stat
		dataType: string
		isHidden
		lineageTag: d4afcd79-d882-4567-9b24-92b6086d7996
		summarizeBy: none
		sourceColumn: Stat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		isHidden
		lineageTag: 62f61a5e-afc8-427e-be4a-649b5f9f8c1b
		summarizeBy: sum
		sourceColumn: Value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Weighted Value'
		dataType: double
		isHidden
		lineageTag: 9c1fd527-f7f0-4359-b701-4348f4e407e5
		summarizeBy: sum
		sourceColumn: Weighted Value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Performance Users' = m
		mode: import
		queryGroup: Performance
		source = ```
				let
				    
				    ADLSPathDelimiter = if #"Is SaaS" then "-" else "/",
				    Source = AzureStorage.DataLake(#"Data Lake URL" & ADLSPathDelimiter & #"License Key"),
				    
				    #"Filtered Rows1" = Table.SelectRows(Source, each (Text.StartsWith([Folder Path], #"Data Lake URL" & ADLSPathDelimiter & #"License Key" & "/log_analytics/perf_by_user/") or (#"Is Demo" and Text.StartsWith([Folder Path], #"Data Lake URL" & "/" & #"License Key" & "/performance/")))),
				    #"Filtered Rows" = if not #"Is Demo" then #"Filtered Rows1" else Table.SelectRows(#"Filtered Rows1", each not Text.StartsWith([Name], "PerfBy") or Text.StartsWith([Name], "PerfByUser")),
				    #"Filter Last N Days" = Table.SelectRows(#"Filtered Rows", each if #"Last N Days Log Analytics" < 0 then true else [Date modified] > Date.AddDays(DateTime.FixedLocalNow(),-#"Last N Days Log Analytics")),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filter Last N Days",{"Content", "Date modified"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "Custom", each Json.Document([Content])),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Added Custom", {"Custom"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Errors",{"Content"}),
				    #"Sorted Rows" = Table.Sort(#"Removed Columns",{{"Date modified", Order.Descending}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Sorted Rows",{{"Date modified", type date}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type2",{{"Date modified", "Date"}}),
				    #"Expanded Custom" = Table.ExpandListColumn(#"Renamed Columns1", "Custom"),
				    
				    Expanded = Table.ExpandRecordColumn(#"Expanded Custom", "Custom",
				        {"ConsumptionMethod", "DurationMs_AVG", "DurationMs_P50", "DurationMs_P75", "DurationMs_P90", "DurationMs_SUM",
				            "PowerBIWorkspaceId", "PowerBIWorkspaceName", "DatasetId", "ReportId", "RunCount", "TableName",
				            "TotalCpuTimeMs_AVG", "TotalCpuTimeMs_P50", "TotalCpuTimeMs_P75", "TotalCpuTimeMs_P90", "TotalCpuTimeMs_SUM", "User", "role", "VisualId"},
				        {"Consumption Method", "Duration_AVG", "Duration_P50", "Duration_P75", "Duration_P90", "Duration_SUM",
				            "PowerBIWorkspaceId", "PowerBIWorkspaceName", "DatasetId", "ReportId", "Run Count", "TableName",
				            "Total CPU Time_AVG", "Total CPU Time_P50", "Total CPU Time_P75", "Total CPU Time_P90", "Total CPU Time_SUM", "User", "Roles", "VisualId"}),
				    
				    #"Removed Duplicates" = Table.Distinct(Expanded, {"Date", "User", "PowerBIWorkspaceId", "ReportId", "VisualId", "Consumption Method"}),
				    
				    #"Filtered Rows2" = Table.SelectRows(#"Removed Duplicates", each [User] <> null and [User] <> ""),
				    #"Added Custom1" = Table.AddColumn(#"Filtered Rows2", "Performance Key", each Text.Lower([ReportId] & "---" & [VisualId])),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom1",{"PowerBIWorkspaceId", "PowerBIWorkspaceName", "ReportId", "DatasetId", "TableName", "VisualId"}),
				
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Columns1", {"User", "Consumption Method", "Date", "Performance Key", "Run Count"}, "Attribute", "Value"),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Unpivoted Other Columns", "Attribute", Splitter.SplitTextByEachDelimiter({"_"}, QuoteStyle.Csv, true), {"Attribute.1", "Attribute.2"}),
				    #"Split Column by Delimiter1" = Table.SplitColumn(#"Split Column by Delimiter", "Attribute.1", Splitter.SplitTextByEachDelimiter({"Ms"}, QuoteStyle.Csv, true), {"Attribute.1.1", "Attribute.1.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"Attribute.1.1", type text}, {"Attribute.1.2", type text}, {"Value", type number}, {"Date", type date}, {"Run Count", Int64.Type}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Changed Type1",{"Attribute.1.2"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns2",{{"Attribute.1.1", "Metric"}, {"Attribute.2", "Stat"}}),
				    #"Convert to Seconds" = Table.AddColumn(#"Renamed Columns", "Value2", each [Value] / 1000, type number),
				    #"Removed Columns3" = Table.RemoveColumns(#"Convert to Seconds",{"Value"}),
				    #"RenamedColumns2" = Table.RenameColumns(#"Removed Columns3",{{"Value2", "Value"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"RenamedColumns2",{{"Run Count", Int64.Type}}),
				    #"Added Weights" = Table.AddColumn(#"Changed Type3", "Weighted Value", each [Run Count] * [Value], type number),
				    
				    LastStep = Table.RenameColumns(#"Added Weights",{{"Run Count", "Log Count"}})
				in
				    LastStep
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

