table Survey
	lineageTag: d3192de8-a4cc-4b0c-b89a-907ddf9e842e

	measure 'Survey Responses' =
			
			VAR _survey_type = MIN('Feedback Type'[Survey type])
			RETURN
			IF(_survey_type = "All Responses", COUNTROWS(Survey), COUNTROWS('Survey Latest'))
		formatString: #,0
		lineageTag: af156833-c87e-432a-b626-aaa898445150

		changedProperty = IsHidden

	measure 'Survey Respondents Multiple' = DISTINCTCOUNT('Survey'[User Key])
		formatString: 0
		isHidden
		lineageTag: 7f4a6761-4989-4036-ae33-8e70b6b699c6

		changedProperty = IsHidden

	measure 'NPS Detractors Multiple' =
			
			CALCULATE(
			    [Survey Respondents Multiple],
			    KEEPFILTERS('Survey Questions'[Order] = 5),
			    KEEPFILTERS('Answers'[Feedback] <= 6)
			)
		formatString: #,0
		isHidden
		lineageTag: 047b247b-75f7-49c8-8861-01bb17a513d1

		changedProperty = IsHidden

	measure 'NPS Promoters Multiple' =
			
			CALCULATE(
			    [Survey Respondents Multiple],
			    KEEPFILTERS('Survey Questions'[Order] = 5),
			    KEEPFILTERS('Answers'[Feedback] >= 9)
			)
		isHidden
		lineageTag: 98c329b5-c3c4-490d-9144-e6e88b4d7943

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NPS Multiple' =
			
			VAR _respondents = [Survey Respondents Multiple]
			VAR PromoterPct = DIVIDE([NPS Promoters Multiple], _respondents, 0)
			VAR DetractorPct = DIVIDE([NPS Detractors Multiple], _respondents, 0)
			RETURN
			(PromoterPct - DetractorPct) * 100
		formatString: #,0.00
		isHidden
		lineageTag: 4c21f820-3ea0-4ee0-8ed0-b0e63a142776

		changedProperty = IsHidden

	measure NPS =
			
			VAR _survey_type = MIN('Feedback Type'[Survey type])
			RETURN
			IF(_survey_type = "All Responses", [NPS Multiple], [NPS Latest] )
		formatString: #,0
		lineageTag: 7fba468a-e416-4893-bce1-92e966bd8f29

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'NPS Detractors' =
			
			VAR _survey_type = MIN('Feedback Type'[Survey type])
			RETURN
			IF(_survey_type = "All Responses", [NPS Detractors Multiple], [NPS Detractors Latest] )
		formatString: #,0
		lineageTag: 9dc7d5d6-7860-4916-a779-0cc00b66ddf2

	measure 'NPS Promoters' =
			
			VAR _survey_type = MIN('Feedback Type'[Survey type])
			RETURN
			IF(_survey_type = "All Responses", [NPS Promoters Multiple], [NPS Promoters Latest] )
		formatString: #,0
		lineageTag: edec7d36-9288-4ef2-97c3-4555b913a48f

	measure 'NPS Max' = 100
		formatString: 0
		isHidden
		lineageTag: e1f53555-5d11-4550-a445-c8fb712f11e2

		changedProperty = IsHidden

	measure 'NPS Min' = -100
		formatString: 0
		isHidden
		lineageTag: 49c8d2b4-ccb3-46ce-bd93-c8046cd3f165

		changedProperty = IsHidden

	measure 'NPS Passives' = [Survey Respondents Multiple] - [NPS Promoters] - [NPS Detractors]
		formatString: #,0
		lineageTag: 04429e25-9007-4ffe-81e9-5e18faaf31fd

	measure 'Survey Financial Gains Multiple' = CALCULATE(SUM('Survey'[Feedback]), KEEPFILTERS('Survey Questions'[Order] = 4), KEEPFILTERS('Answers'[Feedback] >= 0))
		isHidden
		lineageTag: c0934a74-9283-455b-adbd-a4a2cdfa041e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Survey Avg Financial Gains Multiple' = CALCULATE(AVERAGE('Survey'[Feedback]), KEEPFILTERS('Survey Questions'[Order] = 4), KEEPFILTERS('Answers'[Feedback] >= 0))
		formatString: \$#,0;(\$#,0);\$#,0
		isHidden
		lineageTag: 2ba79cf3-e99f-4ca4-96dc-2baceea30e83

		changedProperty = IsHidden

	measure 'Survey Financial Gains' =
			
			VAR _survey_type = MIN('Feedback Type'[Survey type])
			RETURN
			IF(_survey_type = "All Responses", [Survey Financial Gains Multiple], [Survey Financial Gains Latest] )
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b17d4dfa-47cf-4369-a72b-33453d59912a

	measure 'Survey Avg Financial Gains' =
			
			VAR _survey_type = MIN('Feedback Type'[Survey type])
			RETURN
			IF(_survey_type = "All Responses", [Survey Avg Financial Gains Multiple], [Survey Avg Financial Gains Latest] )
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 18e526a3-cbb6-485f-89e8-c876b41a32f9

	measure 'Survey Respondents' =
			
			VAR _survey_type = MIN('Feedback Type'[Survey type])
			RETURN
			IF(_survey_type = "All Responses", [Survey Respondents Multiple], [Survey Respondents Latest] )
		formatString: 0
		lineageTag: 3943d944-032f-46fc-a1f0-16cfe2019b44

	measure 'Survey Time Saving (Hours) Multiple' = CALCULATE(SUM('Survey'[Feedback]), KEEPFILTERS('Survey Questions'[Order] = 2), KEEPFILTERS('Answers'[Feedback] >= 0))
		isHidden
		lineageTag: 72e47d5c-a811-4a30-ac84-4448f0892f0a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Survey Time Savings (Hours)' =
			
			VAR _survey_type = MIN('Feedback Type'[Survey type])
			RETURN
			IF(_survey_type = "All Responses", [Survey Time Saving (Hours) Multiple], [Survey Time Saving (Hours) Latest])
		formatString: #,0
		lineageTag: 613fa530-4e21-4845-bc24-41fc1bf6483a

	measure 'NPS Rating' = ```
			
			VAR _survey_type = MIN('Feedback Type'[Survey type])
			RETURN
			CALCULATE(
			    IF (
			        _survey_type = "All Responses",
			        AVERAGE(Survey[Feedback]),
			        AVERAGE('Survey Latest'[Feedback])
			    ),
			    KEEPFILTERS('Survey Questions'[Question] = "NPS")
			)
			
			```
		formatString: #,0.0
		lineageTag: 3ccbd203-d157-425c-97f5-1153305274a4

	column Feedback
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f6f0f0a9-6c06-46e1-8998-238fa0c136b0
		summarizeBy: none
		sourceColumn: Feedback

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Answer
		dataType: string
		isHidden
		lineageTag: 157c33dd-fa8b-4f15-b235-6f0d506428ff
		summarizeBy: none
		sourceColumn: Answer
		sortByColumn: Feedback

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'User Key'
		dataType: string
		isHidden
		lineageTag: e0f8177d-3bb5-43fe-8441-c8d6dd39982e
		summarizeBy: none
		sourceColumn: User Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		lineageTag: 95124569-2ee6-4568-8d16-d22c6d5baebe
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Time
		dataType: dateTime
		isHidden
		formatString: Long Time
		lineageTag: c926c2c3-7797-48f4-9967-d196d9f938bf
		summarizeBy: none
		sourceColumn: Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Created On'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 322ea13d-b247-4f94-94b8-2bfc6fdaca79
		summarizeBy: none
		sourceColumn: Created On

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Question Key'
		dataType: string
		isHidden
		lineageTag: 207352fb-a376-400e-bc1b-e3731fb1f579
		summarizeBy: none
		sourceColumn: Question Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Report Key'
		dataType: string
		isHidden
		lineageTag: 9c925c25-abb1-4ade-8f09-78d827c7e69e
		summarizeBy: none
		sourceColumn: Report Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Survey = m
		mode: import
		source =
				let
				    Source = #"Feedback - Base",
				    #"Filtered Rows" = Table.SelectRows(Source, each Text.StartsWith([Filtered Column], "'PixieFeedback") and not Text.StartsWith([Filtered Column], "'PixieFeedbackSlicer")),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Feedback Button"}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Columns", "Filtered Column", Splitter.SplitTextByDelimiter("'", QuoteStyle.Csv), {"Prefix", "Question Key"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Split Column by Delimiter",{"Prefix"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Removed Columns1", each ([Question Key] <> "PixieFeedbackContactMe")),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows1",{{"Filtered Values", "Answer"}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns",{"User-Agent", "Visual ID", "Page Index", "Filtered Distinct Count", "Report Page Key", "Platform"})
				in
				    #"Removed Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

