table Users
	lineageTag: 3d7fd907-5510-4672-a204-90916ed8030e

	measure '% Active Users' = DIVIDE([Engaged Users], [Users])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 9d1ea577-7fb3-46da-8e4d-21ce91fdd490

	measure 'WAU (Excluding Passive)' =
			
			VAR _current_week = MAX('Calendar'[Year Week])
			RETURN
			IF (
			    ISFILTERED('Calendar'[Date]),
			    AVERAGEX(
			        VALUES('Calendar'[Year Week]),
			        [Engaged Users]
			    ),
			    CALCULATE(
			        [Engaged Users],
			        FILTER(
			            ALL('Calendar'[Year Week]),
			            'Calendar'[Year Week] = _current_week
			        )
			    )
			)
		formatString: #,0
		lineageTag: d2aa2e82-c63f-4586-af72-4745c7c9fc28

	measure 'WAU / MAU (Excluding Passive)' = DIVIDE ( [WAU (Excluding Passive)], [MAU (Excluding Passive)] )
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: de2b16f5-3189-4c4b-939a-589c41916a2e

	measure '% Passive Users' = 1 - DIVIDE([Engaged Users], [Users])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 73963c67-ce6b-4962-929a-123730ea0e78

	measure DAU =
			
			AVERAGEX ( VALUES ( 'Calendar'[Date] ), [Users] )
		formatString: #,0
		lineageTag: c36dfd91-7658-4e85-9ebf-2adc864dc5a7

	measure 'DAU / MAU' = DIVIDE([DAU], [MAU])
		formatString: #,0.0%;-#,0.0%;#,0.0%
		lineageTag: 24954399-4f58-4939-ab93-b7b283c256d3

	measure 'DAU / MAU (Excluding Passive)' = DIVIDE([DAU (Excluding Passive)], [MAU (Excluding Passive)])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 2f4b593f-7ae3-40bd-b148-ee748f3b2460

	measure 'DAU / WAU' = DIVIDE([DAU], [WAU])
		formatString: #,0.0%;-#,0.0%;#,0.0%
		lineageTag: 3636a5ed-bf82-4436-9a30-1baddbbb6d8b

	measure 'DAU / WAU (Excluding Passive)' = DIVIDE([DAU (Excluding Passive)], [WAU (Excluding Passive)])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: e80afb0a-f294-4d5d-b4c3-f4e45d1e1f97

	measure 'DAU (Excluding Passive)' =
			
			VAR _max_date = max('Report Sessions'[Session Start Date])
			RETURN
			IF (
			    ISFILTERED('Calendar'[Date]),
			    AVERAGEX(VALUES('Calendar'[Date]), [Engaged Users]),
			    CALCULATE([Engaged Users], 'Calendar'[Date] = _max_date)
			)
		formatString: 0
		lineageTag: bce437b5-32e8-422d-9bee-63dd16340889

	measure 'Engaged Users' = ```
			
			COUNTX (
			    Users,
			    [Interactive Page Sessions]
			)
			
			```
		formatString: #,0
		lineageTag: 91b022de-b089-4b84-9c31-b608bb371d91

		changedProperty = IsHidden

	measure MAU =
			
			VAR _max_date = MAX('Calendar'[Date])
			VAR _last_month = FORMAT(_max_date, "YYYY-MM")
			VAR _results = IF (
			    ISFILTERED ( 'Calendar'[Date] ),
			    AVERAGEX ( VALUES ( 'Calendar'[Year Month Val] ), [Users] ),
			    CALCULATE ( [Users], FILTER(ALL('Calendar'[Year Month Val]), 'Calendar'[Year Month Val]  = _last_month ) )
			)
			RETURN
			_results
		formatString: 0
		lineageTag: da710058-d37f-4a6b-a5e9-3c5647faade5

	measure 'MAU (Excluding Passive)' =
			
			VAR _max_date = MAX('Calendar'[Date])
			VAR _last_month = FORMAT(_max_date, "YYYY-MM")
			VAR _results = IF (
			    ISFILTERED ( 'Calendar'[Date] ),
			    AVERAGEX ( VALUES ( 'Calendar'[Year Month Val] ), [Engaged Users] ),
			    CALCULATE ([Engaged Users], FILTER(ALL('Calendar'[Year Month Val]), 'Calendar'[Year Month Val]  = _last_month ) )
			)
			RETURN
			_results
		formatString: #,0
		lineageTag: 7478c931-d86c-4003-9864-04651e4bc79f

	measure 'Passive Users' = [Users] - [Engaged Users]
		formatString: #,0
		lineageTag: 4de70adc-cfbf-4de2-944f-5efb18fcabc0

	measure Users = COUNTX(Users, [Page Sessions] + [Consumer Activities in PBI Logs])
		lineageTag: 58465bb1-cee8-4dae-a19b-7c8460ea4ca9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure WAU =
			
			VAR _current_week = MAX('Calendar'[Year Week])
			RETURN
			IF (
			    ISFILTERED('Calendar'[Date]),
			    AVERAGEX(
			        VALUES('Calendar'[Year Week]),
			        [Users]
			    ),
			    CALCULATE(
			        [Users],
			        FILTER(
			            ALL('Calendar'[Year Week]),
			            'Calendar'[Year Week] = _current_week
			        )
			    )
			)
		formatString: #,0
		lineageTag: 29cadd0b-d697-42b9-b75d-4337aedc1a42

	measure 'WAU / MAU' = DIVIDE ( [WAU], [MAU] )
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 383c7814-6ba4-46d3-833a-5db66b310d6b

	measure 'Cumulative Users' =
			
			VAR max_date = MAX('Calendar'[Date])
			RETURN
			CALCULATE([Users], FILTER(ALL('Calendar'[Date]), 'Calendar'[Date] <= max_date))
		formatString: #,0
		lineageTag: ad4caac8-990f-48cc-a494-60c083d126c4

	measure 'New Users' = ```
			
			    COUNTROWS (
			        FILTER (
			            CALCULATETABLE (
			                ADDCOLUMNS (
			                    VALUES ( Users[User Key] ),
			                    "DateOfFirstUse", CALCULATE ( MIN ( 'Report Sessions'[Session Start Date] ) )
			                ),
			                ALL ( 'Calendar' )
			            ),
			            CONTAINS (
			                VALUES ( 'Calendar'[Date] ),
			                'Calendar'[Date],
			                [DateOfFirstUse]
			            )
			        )
			    )
			
			```
		formatString: #,0
		lineageTag: 0fe569ee-349c-4cfe-850b-973a3ff2e0fc

	measure 'Last-Time Users' = ```
			
			VAR _months_inactivity = [Selected Months]
			VAR _max_date = CALCULATE ( MAX('Calendar'[Date]), ALL('Calendar') )
			VAR _cur_date = MAX('Calendar'[Date])
			VAR _last_inactivity_date = EDATE(_max_date, -_months_inactivity + 1)
			
			VAR _res =
			COUNTROWS (
			    FILTER (
			        CALCULATETABLE (
			            ADDCOLUMNS (
			                VALUES ( Users[User Key] ),
			                "DateOfLastUse", CALCULATE ( MAX ( 'Report Sessions'[Session Start Date] ) )
			            ),
			            ALL ( 'Calendar' )
			        ),
			        CONTAINS (
			            VALUES ( 'Calendar'[Date] ),
			            'Calendar'[Date],
			            [DateOfLastUse]
			        )
			    )
			)
			RETURN
			IF ( _cur_date >= _last_inactivity_date, BLANK(), _res )
			
			```
		formatString: #,0
		lineageTag: 0a701686-cac3-46f1-8e0c-c05f1863f8e3

	measure 'Returning Users' = [Users] - [New Users]
		formatString: #,0
		lineageTag: 31545647-75ed-47d7-9f55-7a9a2025b4b5

	measure 'Cumulative Lost Users' =
			
			VAR _max_date = MIN('Calendar'[Date])
			
			RETURN
			CALCULATE(
			    [Last-Time Users],
			    FILTER (
			        ALL ( 'Calendar'[Date] ),
			        'Calendar'[Date] < _max_date
			    )
			)
		formatString: #,0
		lineageTag: 0871833c-aa69-470d-88f5-d1b63138141c

	measure '% User Attrition' =
			
			VAR _months_inactivity = [Selected Months]
			VAR _max_date = CALCULATE ( MAX('Calendar'[Date]), ALL('Calendar') )
			VAR _cur_date = MAX('Calendar'[Date])
			VAR _last_inactivity_date = EDATE(_max_date, -_months_inactivity)
			RETURN
			IF (_cur_date > _last_inactivity_date, BLANK(),
			DIVIDE([Cumulative Lost Users], [Cumulative Users]))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 6711ecb6-062a-4365-838e-ff22caa61c53

	measure 'Selected User' = SELECTEDVALUE(Users[User Key])
		lineageTag: 89f6d0d2-7873-414b-ae74-a597ff608338

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Days of Inactivity' =
			
			IF(ISBLANK([Users]), BLANK(), DATEDIFF([Last Activity in Period], TODAY(), DAY))
		formatString: 0
		lineageTag: e0be1f16-cb2d-47b3-9838-3a60673b48e9

	measure 'Distribution of Interaction by User' = ```
			
			VAR _min_x = MIN ( 'Interactions X'[Interactions] )
			
			VAR _user_table = SUMMARIZECOLUMNS(
			    Users[User Key],
			    "_AvgInteractions", 
			    IF (
			        ISFILTERED ( 'Pages' ),
			        CALCULATE(
			            [Avg Interactions per Session],
			            ALL ( 'Interactions X' )
			        ),
			        CALCULATE(
			            [Avg Interactions],
			            ALL ( 'Interactions X' )
			        )
			    )
			)
			
			VAR _all_users =
			COUNTROWS(_user_table )
			
			VAR _current_users =
			COUNTROWS (
			    FILTER(
			        _user_table,
			        VAR _avg_interactions = [_AvgInteractions]
			        RETURN
			        _avg_interactions >= _min_x && _avg_interactions < _min_x + 1
			    )
			)
			
			RETURN
			IF (
			    ISBLANK ( _min_x ),
			    BLANK (),
			    DIVIDE (_current_users, _all_users)
			) 
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: e1c20efe-225e-4453-836b-2beabaad59b0

	measure 'Distribution of Duration by User' = ```
			
			VAR _min_set_x = MIN ( 'Durations X'[Duration Set] )
			
			VAR _min_x = CALCULATE (
			    MIN ( 'Durations X'[Duration (Sec)] ),
			    FILTER (
			        ALL ( 'Durations X'[Duration Set] ),
			        'Durations X'[Duration Set] = _min_set_x
			    )
			)
			VAR _max_x = CALCULATE (
			    MAX ( 'Durations X'[Duration (Sec)] ),
			    FILTER (
			        ALL ( 'Durations X'[Duration Set] ),
			        'Durations X'[Duration Set] = _min_set_x
			    )
			)
			
			VAR _user_table =
			SUMMARIZECOLUMNS(
			    Users[User Key],
			    "_AvgDuration", 
			    IF (
			        ISFILTERED ( 'Pages' ),
			        CALCULATE(
			            [Avg Duration in Page (Sec)],
			            ALL ( 'Durations X' )
			        ),
			        CALCULATE(
			            [Avg Session Duration (sec)],
			            ALL ( 'Durations X' )
			        )
			    )
			)
			
			
			VAR _all_users =
			COUNTROWS(_user_table )
			
			VAR _current_users =
			COUNTROWS (
			    FILTER(
			        _user_table,
			        [_AvgDuration] >= _min_x && [_AvgDuration] < _max_x + 1
			    )
			)
			
			RETURN
			IF (
			    ISBLANK ( _current_users ),
			    BLANK (),
			    DIVIDE (_current_users, _all_users)
			) 
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 686c14ba-4a60-424a-9165-cb90fbabe9be

	column 'User Key'
		lineageTag: 7cd93626-e2f2-440b-83e4-367d4e8d567c
		summarizeBy: none
		isNameInferred
		sourceColumn: Events[User Key]

		annotation SummarizationSetBy = Automatic

	partition Users = calculated
		mode: import
		source =
				
				DISTINCT (
				    UNION (
				        SUMMARIZE ( 'Events', 'Events'[User Key] ),
				        SUMMARIZE ( 'Producers Activity', 'Producers Activity'[User Key] ),
				        SUMMARIZE ( 'Consumers Activity', 'Consumers Activity'[User Key] ),
				        SUMMARIZE ( 'Data Exports', 'Data Exports'[User] ),
				        SUMMARIZE ( 'Performance Users', 'Performance Users'[User] ),
				        SUMMARIZE ( 'RLS Events', 'RLS Events'[User Key] )
				    )
				)

	annotation PBI_Id = 1608d8cbee784e8f92b8b94e7deaaa3a

